export * from "./CatalogoOnlineSection"
export * from "./ConectaEntregadorSection"
export * from "./IFoodSection"
export * from "./TaxaEntregaSection"
export * from "./WhatsAppSection"
export * from "./OpcoesEntregaSection"
export * from "./OpcoesPedidoSection"
export * from "./OpcoesPedidoMenuDigitalSection"
