/**
 * Dicionário centralizado de strings da aplicação (UI Strings / i18n Ready).
 * Todas as strings de interface visíveis ao usuário devem ser referenciadas a partir desta constante.
 */

export const UI_STRINGS = {
  common: {
    back: "Voltar",
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    close: "Fechar",
    edit: "Editar",
    delete: "Excluir",
    search: "Buscar...",
    empty: "Vazio",
    loading: "Carregando...",
    currencySymbol: "R$",
    unitDefault: "UN",
    notSelected: "Não selecionado",
    all: "Todos",
    configure: "Configurar",
    adjust: "Ajustar",
    status: "Status",
    skip: "Pular",
    previous: "Anterior",
    next: "Próximo",
    finish: "Finalizar",
    filter: "Filtros",
    filterAction: "Filtrar",
    period: "Período",
    startDate: "Inicial",
    endDate: "Final",
    export: "Exportar",
    menu: "Menu",
    clear: "Limpar",
    apply: "Aplicar",
    synced: "Sincronizado",
    syncTitle: "Sincronização",
    operationStatus: "Status da operação",
    notice: "Aviso",
    copy: "Copiar",
    yourLogo: "Sua Logo",
    administrator: "Administrador",
    dash: "—",
    finishAndBack: "Concluir e Voltar",
    phonePlaceholder: "(00) 00000-0000",
    currencyPlaceholder: "R$ 0,00",
    percentPlaceholder: "% 0,00",
    add: "Adicionar",
    continue: "Continuar",
    subtotal: "Subtotal",
    discount: "Desconto",
    total: "Total",
    observation: "Observação",
    observationPlaceholder: "Digite a observação...",
    discardTitle: "Descartar alterações e sair?",
    discardSubtitle: "Existem alterações não salvas. Se você sair agora, todas as edições serão perdidas.",
    discardConfirm: "Descartar e Sair",
    discardCancel: "Continuar Editando",
  },
  dashboard: {
    title: "Painel Principal",
    salesKpi: "Vendas",
    salesTodaySubtitle: "Hoje - 0 vendas realizadas",
    cashTotalKpi: "Totais em caixa",
    receivablesKpi: "Total a receber",
    receivablesSubtitle: "0 parcelas em aberto",
    digitalAccountKpi: "Conta Digital",
    availableBalance: "Saldo disponível",
    incompleteCompanyTitle: "Dados da Empresa Incompletos",
    incompleteCompanyText: "Pendências encontradas no cadastro: {fields}. Complete as informações para correta identificação nos recibos e pedidos.",
    completeCompanyButton: "Completar cadastro",
    stockDepletedTitle: "Estoque Esgotado: {product}",
    stockDepletedText: "O produto está sem unidades disponíveis em estoque.",
    stockLowTitle: "Estoque Mínimo Atingido: {product}",
    stockLowText: "O produto atingiu o limite mínimo configurado ({stock} de {minStock} {unit} restantes).",
    adjustStockButton: "Ajustar estoque",
  },
  modules: {
    caixa: "Caixa",
    comandas: "Comandas",
    delivery: "Delivery",
    estoque: "Estoque",
    produtos: "Produtos",
    clientes: "Clientes",
    relatorios: "Relatórios",
    config: "Config",
  },
  sidebar: {
    brandName: "Navelo PDV",
    designSystem: "Design System",
    components: "Componentes",
    settings: "Configurações",
    adminName: "Admin Navelo",
    adminEmail: "admin@navelo.com",
    logout: "Sair da conta",
  },
  pdv: {
    header: {
      toggleVisibility: "Ocultar/Mostrar Valores",
      syncedStatus: "Sincronizado com o servidor",
      localModeStatus: "Modo local (alterações pendentes)",
    },
    catalog: {
      searchPlaceholder: "Buscar produtos...",
      searchProductsPlaceholder: "Pesquisar produto pelo nome...",
      noProductsTitle: "Sem produtos",
      noProductsSubtitle: "Nenhum produto cadastrado nesta categoria.",
    },
    drawer: {
      menuTitle: "Menu",
      syncTitle: "Sincronização",
      syncAllSynced: "Todos os dados estão sincronizados",
      syncPendingChanges: "{count} alteração(ões) pendente(s)",
      negotiationHeader: "NEGOCIAÇÃO",
      searchNegotiations: "Buscar negociações",
      lastNegotiations: "Últimas negociações",
      finalizeService: "Finalizar atendimento",
      cancelOperation: "Cancelar operação",
      clientLabel: "Cliente",
      discountOnSale: "Desconto na venda",
      observation: "Observação",
      receipts: "Recebimentos",
      returns: "Devolução",
      otherOperationsHeader: "OUTRAS OPERAÇÕES",
      sangria: "Sangria",
      supply: "Suprimento",
      searchSangrias: "Buscar sangrias/suprimentos",
      cashTotals: "Totais em caixa",
      optionsHeader: "OPÇÕES",
      showOutOfStockProducts: "Exibir produtos sem estoque",
      printerPoints: "Pontos de impressão",
      backToDashboard: "Voltar ao Painel Geral",
    },
    cart: {
      title: "Carrinho",
      emptyTitle: "Carrinho vazio",
      emptySubtitle: "Adicione produtos pelo catálogo ao lado",
      emptyCartSubtitle: "Adicione produtos ao carrinho para iniciar uma venda.",
      subtotal: "Subtotal",
      discount: "Desconto na venda",
      total: "Total",
      payButton: "F9 - Pagamento",
      saveButton: "Salvar",
      saveChangesButton: "Salvar alterações",
    },
    changeCalculator: {
      title: "Calculadora de Troco",
      subtitle: "Calcule o troco a ser entregue ao cliente.",
      totalToPay: "Total a Pagar",
      clientChange: "Troco do Cliente",
      payRemaining: "Pagar restante",
      quickBills: "Cédulas Rápidas",
      bill10: "R$ 10",
      bill20: "R$ 20",
      bill50: "R$ 50",
      bill100: "R$ 100",
      receivedValueLabel: "Valor Recebido (R$)",
      confirmPaymentButton: "Confirmar pagamento",
    },
    checkout: {
      noPaymentsTitle: "Nenhum pagamento lançado",
      subtotal: "Subtotal",
      discountOnSale: "Desconto na venda",
      discount: "Desconto",
      total: "Total",
      totalPaid: "Total pago",
      amountDue: "Falta pagar",
      moneyOptionShort: "D - Dinheiro",
      cardOptionShort: "C - Cartão",
      creditOptionShort: "N - Crediário",
      pixOptionShort: "P - Pix",
      finalizeMobileButton: "Enter ou F9 - Finalizar",
      finalizeSaleButton: "Enter ou F9 - Finalizar Venda",
      accountSummaryTitle: "Resumo da Conta",
      totalToCharge: "Total a Cobrar",
      settlementTitle: "Quitação de Valores",
      settlementTotal: "Total",
      settlementTotalPaid: "Total Pago",
      settlementRemaining: "Restante",
      emptyPaymentsTitle: "Sem pagamentos",
      emptyPaymentsSubtitle: "Nenhum pagamento lançado.",
      removePaymentTitle: "Remover Pagamento",
      removePaymentSubtitle: "Confirmar remoção de pagamento",
      removePaymentParagraph: "Tem certeza que deseja remover este lançamento de pagamento?",
      amountToLaunchLabel: "Valor a Lançar (R$)",
      launchPaymentMethodTitle: "Lançar Forma de Pagamento",
      cashChangeOption: "Dinheiro (Troco)",
      pixInstantOption: "Pix Instantâneo",
      creditDebitOption: "Crédito/Débito",
      crediarioOption: "Crediário Fiado",
    },
    searchPlaceholder: "Pesquisar produto pelo nome...",
    discountShortcutLabel: "F6 - Descontos na Venda",
    modals: {
      exitConfirmTitle: "Deseja salvar a comanda antes de sair?",
      exitConfirmSubtitle: "Você pode salvar as alterações realizadas para continuar depois.",
      exitWithoutSaving: "Sair sem salvar",
      saveAndExit: "Salvar e sair",
      observationTitle: "Observação do Pedido",
      observationPlaceholder: "Digite aqui observações adicionais para a venda...",
      saveObservation: "Salvar observação",
      successSaleTitle: "Venda Concluída!",
      printReceipt: "Imprimir Comprovante",
      finishSale: "Finalizar",
      cardTransactionTitle: "Transação de Cartão",
      debitLabel: "Débito",
      creditLabel: "Crédito",
      amountToLaunchPrefix: "Valor a lançar: {amount}",
      changeCalculatorTitle: "Calculadora de Troco",
      changeCalculatorSubtitle: "Calcule o troco a ser entregue ao cliente.",
      confirmPaymentButton: "Confirmar Pagamento",
      discountModalTitle: "Aplicar desconto",
      discountModalSubtitle: "Informe o valor do desconto a ser aplicado à venda atual.",
      confirmDiscountButton: "Confirmar desconto",
      applyDiscountTitle: "Aplicar desconto",
      percentDiscountLabel: "P - Desconto percentual *",
      reaisDiscountLabel: "R - Desconto em reais",
      discountNotice: "* O desconto do pedido sempre seguirá o percentual informado",
      cancelAction: "Cancelar",
      discountPercentageLabel: "Desconto em Porcentagem (%)",
      discountValueLabel: "Desconto em Valor (R$)",
      discountPercentageInputLabel: "Valor do Desconto (%)",
      discountValueInputLabel: "Valor do Desconto (R$)",
      discountValuePlaceholder: "0,00",
      removeItemTitle: "Remover Item",
      removeItemDesc: "Esta ação removerá o produto desta venda e recalculará o total da conta.",
      paymentMethodLabel: "Forma de Pagamento",
      totalAmountLabel: "Valor Total",
      changeToReturnLabel: "Troco a Devolver",
    },
  },
  settings: {
    identificacao: {
      title: "Identificação",
      visualIdentityTitle: "Identidade visual",
      visualIdentityDesc: "Clique nas áreas indicadas para adicionar a foto de capa e o logo da sua empresa",
      coverPhotoPlaceholder: "Clique para adicionar a foto de capa",
      subdomainLabel: "* Subdomínio",
      subdomainPlaceholder: "basenavelo",
      availableBadge: "Disponível",
      areasPlaceholder: "Áreas atendidas",
      areasDesc: "Descreva as áreas atendidas pela sua empresa",
      colorsTitle: "Cores",
      primaryLightColorDesc: "Cor principal (tema claro)",
      darkThemeToggle: "Disponibilizar tema escuro",
      darkThemeDesc: "Habilite essa opção para que os clientes possam escolher entre o tema claro e o tema escuro.",
      primaryDarkColorDesc: "Cor principal (tema escuro)",
      socialNetworksTitle: "Redes Sociais",
      facebookPlaceholder: "Facebook",
      facebookDesc: "https://www.facebook.com/sua_empresa",
      instagramPlaceholder: "Instagram",
      instagramDesc: "https://www.instagram.com/sua_empresa",
      infoNote: "ℹ️ Estas configurações serão aplicadas tanto para o Menu Digital, quanto para o Catálogo Online.",
    },
    usuarios: {
      title: "Usuários",
      newUserTitle: "Novo Usuário",
      editUserTitle: "Editar Usuário",
      searchPlaceholder: "Buscar usuários...",
      emptyTitle: "Nenhum usuário cadastrado",
      emptySubtitle: "Clique no botão abaixo para adicionar um operador",
      newOperatorButton: "Novo operador",
      nameLabel: "* Nome",
      namePlaceholder: "Digite o nome",
      phoneLabel: "Telefone / Celular",
      phonePlaceholder: "(00) 00000-0000",
      emailLabel: "* E-mail (login)",
      emailPlaceholder: "exemplo@email.com",
      passwordLabel: "* Senha",
      passwordPlaceholder: "Digite a senha",
      commissionLabel: "Comissão (%)",
      commissionPlaceholder: "% 0,00",
      accessProfileTitle: "Perfil de acesso",
      accessProfileDesc: "Defina o nível de permissão deste usuário",
      selectRolePlaceholder: "Selecione o perfil de acesso",
      deleteUserTitle: "Excluir usuário",
      saveUserTitle: "Salvar usuário",
      currentBadge: "Atual",
    },
    unidades: {
      title: "Unidades",
      newUnitTitle: "Nova Unidade",
      editUnitTitle: "Editar Unidade",
      searchPlaceholder: "Buscar unidades...",
      emptyTitle: "Nenhuma unidade cadastrada",
      emptySubtitle: "Clique no botão abaixo para adicionar uma unidade de medida",
      newUnitButton: "Nova unidade",
      nameLabel: "* Sigla / Nome",
      namePlaceholder: "Ex: UN, KG, L, MT",
      decimalsLabel: "* Casas Decimais",
      decimalsDesc: "Define a precisão para pesagem e fracionamento",
      deleteUnitTitle: "Excluir unidade",
      saveUnitTitle: "Salvar unidade",
      zeroDecimals: "0 - Inteiro (Ex: 1 UN)",
      oneDecimal: "1 - Uma casa (Ex: 1.5)",
      twoDecimals: "2 - Duas casas (Ex: 1.25)",
      threeDecimals: "3 - Três casas (Ex: 1.250 KG)",
    },
    formasPagamento: {
      title: "Formas de pagamento",
      advancePaymentTitle: "Pagamento antecipado",
      advancePaymentDesc: "Habilite os meios de pagamento disponíveis na finalização do pedido.",
      digitalAccountTitle: "Conta Digital",
      digitalAccountDesc: "Recebimentos direto em sua conta",
      pixTitle: "Pix",
      pixDesc: "Recebimento instantâneo via QR Code Dinâmico",
      deliveryPaymentTitle: "Pagamento na entrega / balcão",
      deliveryPaymentDesc: "Selecione as formas que o cliente pode pagar na entrega.",
      moneyTitle: "Dinheiro",
      cardTitle: "Cartão (Crédito / Débito na maquininha)",
      pixDeliveryTitle: "Pix na Entrega",
      enabledBadge: "habilitado",
    },
    fornecedores: {
      title: "Fornecedores",
      newSupplierTitle: "Novo Fornecedor",
      editSupplierTitle: "Editar Fornecedor",
      searchPlaceholder: "Buscar fornecedores...",
      emptyTitle: "Nenhum fornecedor cadastrado",
      emptySubtitle: "Clique no botão abaixo para adicionar um fornecedor",
      newSupplierButton: "Novo fornecedor",
      generalDataTitle: "Dados Gerais",
      tradeNameLabel: "Nome fantasia",
      tradeNamePlaceholder: "Nome fantasia",
      companyNameLabel: "* Razão social",
      companyNamePlaceholder: "Razão social",
      documentLabel: "CPF / CNPJ",
      documentPlaceholder: "00.000.000/0000-00",
      stateRegLabel: "Inscrição Estadual",
      stateRegPlaceholder: "Inscrição estadual",
      phoneLabel: "Telefone / Celular",
      phonePlaceholder: "(00) 00000-0000",
      addressTitle: "Endereço",
      cepLabel: "CEP",
      cepPlaceholder: "00000-000",
      streetLabel: "Logradouro / Rua",
      streetPlaceholder: "Rua, avenida...",
      numberLabel: "Número",
      numberPlaceholder: "123",
      complementLabel: "Complemento",
      complementPlaceholder: "Apto, sala, bloco...",
      neighborhoodLabel: "Bairro",
      neighborhoodPlaceholder: "Bairro",
      cityLabel: "Cidade / UF",
      cityPlaceholder: "Cidade / UF",
      deleteSupplierTitle: "Excluir fornecedor",
      saveSupplierTitle: "Salvar fornecedor",
    },
    gruposSubgrupos: {
      title: "Grupos e Subgrupos",
      newGroupTitle: "Novo Grupo",
      editGroupTitle: "Editar Grupo",
      searchPlaceholder: "Buscar grupos...",
      emptyTitle: "Nenhum grupo cadastrado",
      emptySubtitle: "Clique no botão abaixo para adicionar um grupo e subgrupos",
      newGroupButton: "Novo grupo",
      groupNameLabel: "* Nome do grupo",
      groupNamePlaceholder: "Ex: BEBIDAS, LANCHES, PIZZAS...",
      subgroupsTitle: "Subgrupos (opcional)",
      subgroupsDesc: "Adicione subcategorias para organizar melhor seus produtos no cardápio",
      subgroupPlaceholder: "Ex: REFRIGERANTES, SUCOS...",
      addSubgroupButton: "Adicionar subgrupo",
      deleteGroupTitle: "Excluir grupo",
      saveGroupTitle: "Salvar grupo",
    },
    clientes: {
      title: "Clientes",
      searchPlaceholder: "Buscar por nome ou CPF/CNPJ...",
      emptyTitle: "Nenhum cliente encontrado",
      emptySubtitle: "Cadastre seu primeiro cliente para gerenciar no PDV.",
      noDocumentText: "Sem documento",
      cpfCnpjTemplate: "CPF/CNPJ: {document}",
    },
  },
  fiscal: {
    title: "Nota Fiscal",
    settingsTitle: "Configurações Fiscais",
    companyDataTitle: "Dados da Empresa Emissora",
    documentLabel: "CNPJ",
    cpfCnpjAuthorizedTitle: "CPF/CNPJ autorizada a obter o XML",
    noAuthorizedDocTitle: "Nenhum documento autorizado",
    noAuthorizedDocSubtitle: "Adicione um CPF ou CNPJ para permitir download do XML",
    addCpfCnpjAuthorizedButton: "CPF/CNPJ autorizado",
    stateRegLabel: "Inscrição Estadual",
    taxRegimeLabel: "Regime Tributário",
    nfceTitle: "Série/Número NFC-e (Utilize uma configuração única para cada dispositivo)",
    nfceDesc: "Configurações para emissão automática de cupom fiscal ao finalizar a venda",
    enableEmissionToggle: "Habilitar emissão de notas",
    enableEmissionDesc: "Ative para realizar a emissão de cupons e notas fiscais de venda",
    cscIdLabel: "Identificador do CSC (ID)",
    cscTokenLabel: "Código de Segurança do Contribuinte (CSC)",
    serieLabel: "Série NFC-e *",
    nextNumberLabel: "Último número NFC-e *",
    nfeSerieLabel: "Série NF-e *",
    nfeNextNumberLabel: "Último número NF-e *",
    nfeTitle: "Série/Número NF-e (Utilize uma configuração única para cada dispositivo)",
    nfeDesc: "Configurações para emissão de nota fiscal grande com transporte e faturamento",
    digitalCertTitle: "Certificado digital (arquivo .pfx) *",
    digitalCertDesc: "Faça o upload do arquivo .pfx ou .p12 para assinatura digital",
    uploadCertButton: "Selecionar Certificado",
    certPasswordLabel: "Senha do Certificado",
    certPasswordPlaceholder: "Digite a senha do certificado",
    environmentLabel: "Ambiente",
    productionOption: "Produção",
    homologationOption: "Ambiente de homologação",
    autoIssueToggle: "Emitir NF-e automaticamente para pessoa jurídica (CNPJ)",
    printNonFiscalAfterDanfe: "Imprimir comprovante não fiscal após a DANFE",
    cancelReasonLabel: "Motivo de cancelamento *",
    additionalInfoLabel: "Informações adicionais",
    sendEmailToggle: "Enviar XML e DANFE automaticamente para o e-mail do cliente",
    posInfoTitle: "Informações POS",
    posInfoDesc: "Este recurso solicitará o preenchimento das informações de POS ao finalizar a venda.",
    enablePosToggle: "Habilitar",
    requiredFieldsTitle: "Campos obrigatórios:",
    posInstitutionLabel: "Instituição financeira",
    posCardBrandLabel: "Bandeira do cartão",
    posAuthNumberLabel: "Número de autorização",
    financialInstitutionsTitle: "Instituições financeiras:",
    institutionPlaceholder: "Nome da instituição",
    addInstitutionButton: "Adicionar instituição financeira",
    defaultCscOption: "CSC Padrão",
    defaultCancelReason: "Operação cancelada pelo cliente",
    simplesNacionalOption: "Simples Nacional",
    lucroPresumidoOption: "Lucro Presumido",
    lucroRealOption: "Lucro Real",
    defaultFiscalConfigTitle: "Configuração fiscal padrão",
    defaultFiscalConfigDesc: "Defina os impostos herdados pelos produtos configurados como padrão",
    saveDefaultsButton: "Salvar Padrões",
    defaultFiscalConfigNotice: "Os parâmetros definidos abaixo serão aplicados automaticamente para qualquer produto que tiver as opções de utilizar ICMS ou PIS/COFINS padrão marcadas em seu formulário de cadastro.",
    csosnIcmsRequired: "CSOSN ICMS *",
    csosn101: "101 - Simples Nacional sem permissão de crédito",
    csosn102: "102 - Simples Nacional sem permissão de crédito (outros)",
    csosn500: "500 - ICMS cobrado anteriormente por substituição tributária (substituído)",
    reductionBaseLabel: "Redução da base de cálculo efetiva (%)",
    aliquotIcmsLabel: "Alíquota do ICMS efetiva (%)",
    cstPisCofinsRequired: "CST PIS/COFINS *",
    pis01: "01 - Operação Tributável com Alíquota Básica",
    pis49: "49 - Outras Operações de Saída",
    pis99: "99 - Outras Operações",
  },
  printers: {
    title: "Impressoras",
    newPrinterTitle: "Nova Impressora",
    editPrinterTitle: "Editar Impressora",
    searchPlaceholder: "Buscar impressoras...",
    emptyTitle: "Nenhuma impressora configurada",
    emptySubtitle: "Adicione uma impressora de rede ou USB para imprimir pedidos e comprovantes",
    nameLabel: "* Nome da Impressora",
    namePlaceholder: "Ex: Cozinha, Caixa, Bar...",
    typeLabel: "* Tipo de Conexão",
    networkOption: "Rede / IP (Ethernet / Wi-Fi)",
    usbOption: "USB / Local",
    bluetoothOption: "Bluetooth",
    ipAddressLabel: "* Endereço IP",
    ipAddressPlaceholder: "192.168.1.100",
    portLabel: "* Porta",
    portPlaceholder: "9100",
    paperWidthLabel: "* Largura do Papel",
    width80mm: "80mm (Padrão)",
    width58mm: "58mm (Estreito)",
    testPrintButton: "Testar Impressão",
    compatibilityModeLabel: "Modo de compatibilidade",
    disabledDefaultOption: "Desabilitado (Padrão)",
    escposOption: "ESC/POS Compatível",
    increaseFontLabel: "Aumentar fonte da impressão",
    columnsNumberLabel: "Número de colunas",
    enableDrawerToggle: "Habilitar gaveta de dinheiro",
    printerModelLabel: "Modelo da impressora",
    customOption: "Personalizado",
    bematechOption: "Bematech",
    elginOption: "Elgin",
    drawerCommandLabel: "* Comando de abertura da gaveta",
    drawerCommandPlaceholder: "Ex: 27,112,0,50,250",
    deletePrinterTitle: "Excluir impressora",
    savePrinterTitle: "Salvar impressora",
    testPrintTitle: "Impressão de teste",
    simulationSubtitle: "Simulação",
    sendingTestPrint: "Enviando impressão de teste...",
  },
  thermalReceipt: {
    receiptPreviewTitle: "Pré-visualização do Cupom",
    paperWidth: "Bobina 80mm",
    sampleCompany: "NAVELO TECNOLOGIA LTDA",
    sampleCnpj: "12.345.678/0001-99",
    sampleAddress: "RUA DAS FLORES, 123 - CENTRO - SP",
    nfeTitle: "CUPOM FISCAL ELETRÔNICO (NFC-e)",
    itemHeader: "ITEM",
    qtyHeader: "QTD",
    valueHeader: "VALOR",
    subtotal: "Subtotal",
    approxTaxes: "Tributos Aprox. (12%)",
    totalValue: "VALOR TOTAL",
    paymentMethod: "FORMA PAGTO.",
    sampleNfce: "NFC-e Nº 000184 Série 001",
    sampleEmission: "Emissão: 26/06/2026 01:52",
    consumerCopy: "Via Consumidor",
    accessKeyPrompt: "Consulte pelo QR Code ou Chave de Acesso:",
    sampleAccessKey: "3526 0612 3456 7800 0199 6500 1000 0001 8410 0234 5678",
  },
  printPoints: {
    title: "Pontos de Impressão",
    newPointTitle: "Novo Ponto de Impressão",
    editPointTitle: "Editar Ponto de Impressão",
    searchPlaceholder: "Buscar pontos...",
    emptyTitle: "Nenhum ponto de impressão cadastrado",
    emptySubtitle: "Defina para onde cada categoria de produto deve ter seus pedidos impressos",
    nameLabel: "* Nome do Ponto",
    namePlaceholder: "Ex: Balcão, Cozinha Quente, Sushibar...",
    printerLabel: "* Impressora de Destino",
    selectPrinterPlaceholder: "Selecione a impressora",
    categoriesLabel: "* Categorias Vinculadas",
    autoPrintToggle: "Imprimir automaticamente ao confirmar pedido",
    copiesLabel: "Número de Vias",
    deletePointTitle: "Excluir ponto de impressão",
    savePointTitle: "Salvar ponto de impressão",
    increaseFontToggle: "Aumentar fonte da impressão",
    columnsLabel: "Número de colunas",
    ipPrinterDesc: "Endereço IP da impressora.",
    kitchenMonitorTitle: "Habilitar Monitor de Cozinha",
    linkingCodeLabel: "Código de vinculação",
    linkingCodePlaceholder: "Digite o código...",
    linkButton: "VINCULAR",
    kitchenAppDesc: "Gere o código de vinculação no aplicativo 'Monitor de Cozinha'.",
    selectedProductsDesc: "1 produto selecionado.",
  },
  pix: {
    title: "Configurações do Pix",
    keyTitle: "Chave Pix",
    keyTypeLabel: "* Tipo de Chave",
    cpfCnpjOption: "CPF / CNPJ",
    emailOption: "E-mail",
    phoneOption: "Telefone",
    randomKeyOption: "Chave Aleatória",
    keyLabel: "* Chave",
    keyPlaceholder: "Digite a sua chave Pix",
    holderNameLabel: "* Nome do Titular da Conta",
    holderNamePlaceholder: "Nome completo ou Razão Social",
    cityLabel: "* Cidade do Titular",
    cityPlaceholder: "Cidade cadastrada na conta",
    autoConfirmTitle: "Confirmação Automática",
    autoConfirmDesc: "Integração via API bancária para validação instantânea do pagamento sem necessidade de envio de comprovante",
    bankProviderLabel: "Instituição / Gateway",
    selectProviderPlaceholder: "Selecione a instituição",
    clientIdLabel: "Client ID",
    clientSecretLabel: "Client Secret",
    cashierChannelLabel: "Caixa",
    onlineCatalogChannelLabel: "Catálogo Online",
  },
  ifood: {
    title: "Integração iFood",
    optionsTitle: "Opções",
    connectionStatusTitle: "Status da Conexão",
    connectedBadge: "Conectado",
    disconnectedBadge: "Desconectado",
    merchantIdLabel: "* Merchant ID da Loja",
    merchantIdPlaceholder: "ID da loja no iFood Portal",
    autoAcceptToggle: "Aceitar pedidos automaticamente",
    autoAcceptDesc: "Os pedidos que entrarem no iFood serão confirmados e impressos de imediato",
    autoDispatchToggle: "Despacho automático para entregadores",
    syncMenuTitle: "Sincronização de Cardápio",
    syncMenuDesc: "Envie seus produtos e preços do Navelo diretamente para o catálogo do iFood",
    syncNowButton: "Sincronizar Cardápio Agora",
    disabledNotice: "Habilite a integração com o iFood para buscar as informações do restaurante.",
    menuItemTitle: "Cardápio",
    cleanMenuTitle: "Limpar cardápio no iFood",
    notificationCheckboxLabel: "Notificação",
    notificationDesc: "Receberá uma notificação quando um novo pedido for recebido do iFood.",
    soundAlertCheckboxLabel: "Habilitar aviso sonoro",
    soundAlertDesc: "Será emitido um aviso sonoro quando um novo pedido for recebido do iFood.",
    continuousSoundCheckboxLabel: "Aviso sonoro contínuo",
    continuousSoundDesc: 'O aviso sonoro será contínuo até que o pedido seja alterado para "Aberto" ou excluído.',
    activationModalTitle: "Ativar aplicativo",
    activationModalSubtitle: "Vincule sua conta iFood com o Navelo PDV",
    activationCodeLabel: "Código de ativação",
    step1Instruction: "Acesse a URL abaixo e cole o código de ativação na plataforma do iFood para ativar o aplicativo.",
    step2Instruction: "Para concluir a ativação do aplicativo, informe o código de ativação gerado pelo iFood.",
    activationCodeInputLabel: "* Código de ativação",
    activationCodeInputPlaceholder: "Cole o código retornado pelo iFood",
    mockActivationCode: "PDDD-FPSG",
    portalUrl: "https://portal.ifood.com.br/apps/code",
  },
  whatsapp: {
    title: "Integração WhatsApp",
    connectionTitle: "Conexão com WhatsApp",
    scanQrCodeTitle: "Escaneie o QR Code com seu WhatsApp",
    scanQrCodeDesc: "Abra o WhatsApp no seu celular > Configurações > Aparelhos Conectados > Conectar um aparelho",
    connectedStatus: "Dispositivo Conectado com Sucesso",
    disconnectButton: "Desconectar WhatsApp",
    notificationsTitle: "Notificações Automáticas para Clientes",
    orderConfirmedToggle: "Enviar mensagem quando o pedido for confirmado",
    orderDispatchedToggle: "Enviar mensagem quando o pedido sair para entrega",
    orderReadyToggle: "Enviar mensagem quando o pedido estiver pronto para retirada",
    step1: "Abra o WhatsApp no seu celular",
    step2: "Toque em Menu (três pontos) ou Configurações",
    step3: "Selecione \"Dispositivos conectados\"",
    step4: "Toque em \"Conectar um dispositivo\"",
    step5: "Aponte a câmera para o QR Code exibido na tela",
  },
  integratedPayment: {
    title: "Pagamento Integrado (TEF / Maquininha)",
    providerTitle: "Provedor de Pagamento",
    selectProviderPlaceholder: "Selecione o provedor TEF / POS",
    terminalIdLabel: "* ID do Terminal / Número de Série",
    terminalIdPlaceholder: "Digite o identificador da maquininha",
    autoSendAmountToggle: "Enviar valor da venda automaticamente para a maquininha",
    printVoucherToggle: "Imprimir comprovante do cartão na impressora do caixa",
  },
  delivery: {
    title: "Delivery e Entregas",
    enableDeliveryToggle: "Habilitar módulo de Delivery",
    enableDeliveryDesc: "Permite controle de pedidos para entrega e expedição de motoboys",
    deliveryFeeLabel: "Taxa padrão de entrega",
    estimatedTimeLabel: "Tempo estimado de entrega (min)",
    minOrderValueLabel: "Valor mínimo do pedido",
    emptyTitle: "Nenhum pedido de delivery",
    emptySubtitle: "Clique no botão + abaixo para iniciar um novo pedido pelo caixa.",
    noOrderSelectedTitle: "Sem pedido selecionado",
    noOrderSelectedSubtitle: "Selecione um pedido de delivery para visualizar os detalhes.",
    searchPlaceholder: "Buscar por cliente ou ID...",
    printOrderTitle: "Imprimir pedido",
    ridersTitle: "Entregadores / Motoboys",
    newRiderTitle: "Novo Entregador",
    editRiderTitle: "Editar Entregador",
    riderNameLabel: "* Nome do Entregador",
    riderPhoneLabel: "Telefone / WhatsApp",
    riderVehicleLabel: "Veículo / Placa",
    deliveryAndPayment: "Entrega/Cobrança",
    riderSection: "Entregador",
    selectRiderAction: "SELECIONAR",
    itemsSection: "Itens",
    totalsSection: "Totais",
    itemsTotal: "Valor itens",
    deliveryFee: "Taxa de entrega",
    discount: "Desconto",
    totalToPay: "Total a pagar",
    totalPaid: "Total pago",
    motoboyWarningTitle: "Entregador não selecionado",
    motoboyWarningSubtitle: "Selecione um entregador parceiro para iniciar a entrega deste pedido.",
    motoboyWarningSuccess: "Selecionar entregador",
    motoboyWarningBody: "Não é possível alterar o status do pedido para 'Saiu para entrega' sem que haja um entregador atribuído ao pedido.",
    clientSelectModalTitle: "Identificar Cliente do Delivery",
    clientSelectModalSubtitle: "Selecione um cliente cadastrado ou preencha os dados da entrega",
    advanceToOrderButton: "Avançar para o Pedido",
    searchRegisteredTab: "Buscar Cadastrado",
    clientDataTab: "Dados do Cliente",
    searchClientPlaceholder: "Buscar por nome, telefone ou CPF/CNPJ...",
    noRegisteredClientTitle: "Nenhum cliente cadastrado",
    noRegisteredClientSubtitle: "Tente buscar por outro termo ou cadastre um novo cliente.",
    defaultStatusOpen: "Status do pedido: Aberto",
    changeStatusTitle: "Alterar status",
    statusLabelRequired: "* Status",
    deliveryTypeRequired: "* Tipo de entrega",
    clientRequired: "* Cliente",
    alterAction: "ALTERAR",
    clearAction: "LIMPAR",
    clientNotInformed: "Cliente não informado",
    addressNotInformed: "Endereço não informado",
    selectRiderPlaceholder: "Selecione um entregador",
    noDeliveryFeeInformed: "Nenhuma taxa de entrega informada",
    paymentMomentRequired: "* Momento da cobrança",
    confirmOrderF9: "F9 – Confirmar pedido",
    clientNamePlaceholder: "Nome do cliente",
    deliveryAddressPlaceholder: "Endereço de entrega",
    totalValuePlaceholder: "Valor total (R$)",
    submitOrderButton: "Lançar Pedido",
    ordersSectionTitle: "Pedidos",
    filterByStatusTitle: "Filtrar por status",
    searchRiderPlaceholder: "Buscar por entregador...",
    riderNamePlaceholder: "* Nome do Entregador",
    riderDocumentPlaceholder: "CPF/CNPJ do Entregador",
    enableConectaToggle: "Habilitar entregador no Conecta Entregador",
    conectaCodePlaceholder: "Código de vinculação",
    linkRiderTitle: "Vincular entregador",
    conectaCodeHelpText: "Insira o código de vinculação do aplicativo Conecta Entregador.",
    deleteRiderTitle: "Excluir entregador",
    saveRiderButton: "Salvar entregador",
    emptyRidersTitle: "Nenhum entregador cadastrado",
    emptyRidersSubtitle: "Clique no botão + abaixo para cadastrar um novo entregador.",
  },
  tables: {
    title: "Mesas e Comandas",
    enableTablesToggle: "Habilitar controle de Mesas",
    enableComandasToggle: "Habilitar controle de Comandas",
    tablesCountLabel: "Quantidade de Mesas",
    comandasCountLabel: "Quantidade de Comandas",
    autoCloseTableToggle: "Liberar mesa automaticamente após pagamento total",
    couvertLabel: "Valor do Couvert Artístico (por pessoa)",
    serviceTaxPercentLabel: "Taxa de Serviço (%)",
    searchComandaPlaceholder: "Pesquisar comanda ativa...",
    emptyComandasTitle: "Nenhuma comanda ativa",
    emptyComandasSubtitle: "Abra uma comanda pelo menu para iniciar o consumo.",
    disableNotice: "Ao desabilitar, o módulo de mesas e comandas não ficará acessível para vendas.",
    serviceTypePlaceholder: "Tipo de atendimento",
    bothTablesTabsOption: "Mesas e Comandas",
    tablesOnlyOption: "Somente Mesas",
    consumptionRulesTitle: "Regras de Consumo",
    limitConsumptionCheckboxLabel: "Limitar consumo por atendimento",
    consumptionLimitLabel: "Limite de consumo",
    consumptionLimitDesc: "Ao ultrapassar o limite, será necessária autorização de administrador.",
    serviceHeader: "ATENDIMENTO",
    newAvulsoService: "Novo atendimento avulso",
    finishServices: "Finalizar atendimentos",
    newServiceTitle: "Novo Atendimento",
    comandaIdentifierLabel: "Identificador da Comanda",
    comandaIdentifierPlaceholder: "Ex: #mesa_14, #pedro...",
    confirmAndOpenButton: "Confirmar e Abrir",
    saveTabButton: "Salvar Comanda",
    newComandaButton: "Nova Comanda",
    identifierInputPlaceholder: "Identificador",
    identifierInputHint: "[identificador] + [Enter]",
    suggestionsHeader: "Sugestões encontradas:",
    batchFinishButton: "F9 - Finalizar",
    batchFinishTitle: "Finalizar atendimentos",
  },
  orderOptions: {
    title: "Opções de Pedido",
    askCustomerNameToggle: "Solicitar identificação do cliente no início da venda",
    askTableNumberToggle: "Solicitar número da mesa ou comanda",
    printOrderOnSaveToggle: "Imprimir comanda de produção ao salvar",
    allowDiscountsToggle: "Permitir desconto manual no fechamento",
    requirePasswordForDiscountToggle: "Exigir senha de supervisor para conceder desconto",
    allowOnlineOrdersDesc: "O cliente fará pedidos para a mesa ou comanda através do Menu Digital.",
    deviceReceivingOrdersLabel: "Dispositivo que receberá os pedidos",
    selectDevicePlaceholder: "Selecione um dispositivo",
    deviceReceivingNotice: "ℹ️ O dispositivo selecionado receberá tanto os pedidos do Menu Digital, quanto do Catálogo Online.",
    loginDesc: "Será obrigatório o login para realizar pedidos e acessar histórico, cartões e endereços.",
    blockOutOfHoursToggle: "Bloquear pedidos fora do horário",
    blockOutOfHoursDesc: "Não será possível realizar pedidos fora do horário de atendimento.",
    notificationToggle: "Notificação",
    notificationDesc: "Receberá uma notificação quando um novo pedido for recebido do Catálogo Online.",
    soundAlertToggle: "Aviso sonoro",
    soundAlertDesc: "Será emitido um aviso sonoro quando um novo pedido for recebido.",
    continuousSoundToggle: "Aviso sonoro contínuo",
    continuousSoundDesc: "O aviso sonoro será contínuo até que o pedido do Catálogo Online seja alterado para \"Aberto\" ou excluído.",
    deviceSelectorLabel: "Dispositivo que receberá os pedidos",
    deviceInfoNote: "ℹ️  O dispositivo selecionado receberá tanto os pedidos do Catálogo Online, quanto do Menu Digital.",
    digitalMenuInfoNote: "ℹ️ O dispositivo selecionado receberá tanto os pedidos do Menu Digital, quanto do Catálogo Online.",
    menuDigitalOrderDesc: "O cliente fará pedidos para a mesa ou comanda através do Menu Digital.",
    device06: "Dispositivo 06",
    device01: "Dispositivo 01",
    mainCashierDevice: "Caixa Principal",
  },
  schedule: {
    title: "Horário de Atendimento",
    scheduleDesc: "Defina os dias e horários em que seu estabelecimento estará aberto para receber pedidos.",
    operatingHoursTitle: "Horários de Funcionamento",
    dayMonday: "Segunda-feira",
    dayTuesday: "Terça-feira",
    dayWednesday: "Quarta-feira",
    dayThursday: "Quinta-feira",
    dayFriday: "Sexta-feira",
    daySaturday: "Sábado",
    daySunday: "Domingo",
    closedStatus: "Fechado",
    openStatus: "Aberto",
    openTimeLabel: "Abertura",
    closeTimeLabel: "Fechamento",
    toTimeSeparator: "às",
  },
  digitalMenu: {
    title: "Menu Digital (Cardápio Online)",
    enableMenuToggle: "Habilitar Cardápio Digital Online",
    menuUrlLabel: "Link do seu Cardápio",
    copyUrlButton: "Copiar Link",
    bannerTitle: "Banner Principal",
    welcomeMessageLabel: "Mensagem de Boas-vindas",
    allowOnlineOrdersToggle: "Permitir que clientes façam pedidos pelo cardápio",
    headerDesc: "Você terá uma página na internet com os seus produtos e com a cara da sua loja.",
    openInBrowserTooltip: "Abrir no navegador",
    copiedTooltip: "Copiado!",
    selectedProductsTemplate: "{count} produtos selecionados",
    selectedProductsCountTemplate: "{count} produtos selecionados",
  },
  weighing: {
    title: "Pesagem Automática",
    enableScaleToggle: "Habilitar integração com Balança",
    scaleModelLabel: "* Modelo da Balança",
    baudRateLabel: "* Taxa de Transmissão (Baud Rate)",
    comPortLabel: "* Porta Serial (COM)",
    tareWeightLabel: "Tara padrão do prato (kg)",
    testWeightButton: "Ler Peso da Balança",
    authSectionTitle: "Autenticação",
    passwordLabel: "* Senha",
    passwordPlaceholder: "Senha",
    authDesc: "Cadastre a senha que será utilizada para acessar as configurações do aplicativo Pesagem Automática.",
    mainProductTitle: "Produto Principal",
    selectProductPlaceholder: "Selecione um produto",
    enableBuffetToggle: "Habilitar buffet livre",
    buffetFreeTitle: "Buffet Livre",
    linkedDevicesTitle: "Dispositivos vinculados",
    enableDevicesToggle: "Habilitar dispositivos",
    emptyDevicesTitle: "Nenhum dispositivo vinculado",
    emptyDevicesSubtitle: "Vincule um dispositivo para disponibilizar a Pesagem Automática.",
    disabledDevicesTitle: "Dispositivos desabilitados",
    disabledDevicesSubtitle: "Ative a chave acima para gerenciar dispositivos vinculados à Pesagem Automática.",
    linkDeviceButton: "Vincular dispositivo",
    appName: "Pesagem Automática",
  },
  fees: {
    title: "Taxas e Acréscimos",
    deliveryFeeTitle: "Taxas de Entrega",
    serviceFeeTitle: "Taxa de Serviço",
    serviceFeeToggle: "Cobrar taxa de serviço sobre o total",
    serviceFeePercentageLabel: "Percentual da Taxa (%)",
    serviceFeeDistributionDesc: "O valor será discriminado na conta e destinado aos atendentes",
  },
  deliveryOptions: {
    title: "Opções de Entrega",
    pickupOptionLabel: "Retirada no local",
    pickupOptionDesc: "O cliente terá a opção de retirada no estabelecimento.",
    deliveryOptionLabel: "Entrega",
    deliveryOptionDesc: "O cliente terá a opção de receber o pedido no endereço informado.",
    dineInOptionLabel: "Consumir no local",
    dineInOptionDesc: "O cliente terá a opção de consumir o pedido no local.",
    deliveryFeeNotice: "As taxas serão exibidas como região de entrega no Catálogo Online.",
  },
  restrictions: {
    title: "Restrições e Bloqueios",
    blockNegativeStockToggle: "Bloquear venda de produtos sem estoque",
    blockSaleWithoutCustomerToggle: "Exigir CPF na nota para vendas acima do limite legal",
    requireSupervisorForCancelToggle: "Exigir autorização do supervisor para cancelar itens ou vendas",
    actionsTitle: "Ações",
    reprintToggle: "Reimpressão de tickets",
    transferToggle: "Transferência de produtos entre mesas",
    complementToggle: "Cadastrar itens de complemento na venda",
    discountToggle: "Aplicar descontos",
    discountLimitLabel: "Limite de desconto permitido ao usuário",
  },
  customers: {
    title: "Clientes",
    newCustomerTitle: "Novo Cliente",
    editCustomerTitle: "Editar Cliente",
    searchPlaceholder: "Buscar por nome, CPF/CNPJ ou telefone...",
    emptyTitle: "Nenhum cliente cadastrado",
    emptySubtitle: "Cadastre novos clientes para gerenciar o histórico de compras e entregas.",
    cpfCnpjTemplate: "CPF/CNPJ: {document}",
    noDocumentText: "Sem documento",
    emptyAddressTitle: "Nenhum endereço cadastrado",
    emptyAddressSubtitle: "Adicione um endereço para o cliente.",
    editAddressTitle: "Editar endereço",
    deleteAddressConfirmTitle: "Excluir Endereço",
    deleteAddressConfirmSubtitle: "Confirmar exclusão de endereço",
    deleteAddressConfirmParagraph: "Tem certeza que deseja remover este endereço do cliente? Esta ação não poderá ser desfeita.",
    deleteAddressTitle: "Excluir endereço",
    defaultAddressBadge: "Padrão",
    addressModalTitleNew: "Dados do endereço",
    addressModalTitleEdit: "Editar Endereço",
    addressModalSubtitle: "Preencha as informações do endereço para entregas.",
    addressNameLabel: "* Nome do Endereço",
    addressNamePlaceholder: "Ex: Casa, Trabalho",
    cepLabel: "CEP",
    cepPlaceholder: "00000-000",
    streetLabel: "Logradouro",
    streetPlaceholder: "Rua, Avenida...",
    numberLabel: "Número",
    numberPlaceholder: "Ex: 123",
    complementLabel: "Complemento",
    complementPlaceholder: "Apto, Bloco...",
    neighborhoodLabel: "Bairro",
    neighborhoodPlaceholder: "Nome do bairro",
    cityLabel: "* Cidade",
    cityPlaceholder: "Nome da cidade",
    addButton: "Adicionar",
    deleteCustomerConfirmTitle: "Excluir Cliente",
    deleteCustomerConfirmSubtitle: "Confirmar exclusão de cadastro",
    deleteCustomerConfirmParagraph: "Tem certeza de que deseja excluir este cliente do sistema? Esta ação não poderá ser desfeita.",
    deleteCustomerButtonTitle: "Excluir cliente",
    searchRegisteredCustomerPlaceholder: "Buscar cliente cadastrado...",
    saveClientInList: "Salvar cliente na lista",
    noCustomerFoundTitle: "Nenhum cliente encontrado",
    noCustomerFoundSubtitle: "Tente pesquisar com outro termo ou limpe a busca para cadastrar um novo cliente.",
    personalDataTitle: "Dados pessoais",
    nameRequiredPlaceholder: "* Nome",
    emailPlaceholder: "E-mail",
    cpfPlaceholder: "CPF",
    phonePlaceholder: "Telefone",
    addressTitle: "Endereço",
    addAddressTitle: "Adicionar endereço",
  },
  receivables: {
    title: "Contas a receber",
    searchPlaceholder: "Buscar por cliente ou documento...",
    emptyTitle: "Nenhuma conta a receber encontrada",
    emptySubtitle: "Os pagamentos a prazo e boletos pendentes aparecerão listados aqui",
    amountDueLabel: "Valor a Receber",
    dueDateLabel: "Vencimento",
    settleButton: "Liquidar Conta",
    periodTypeLabel: "Tipo de período",
    clientLabel: "Cliente",
    clientPlaceholder: "Cliente",
    deviceLabel: "Dispositivo",
    devicePlaceholder: "Dispositivo",
    filtersPanelTitle: "Filtros",
    toReceiveLabel: "A receber",
    settledLabel: "Liquidado",
    docPrefix: "Doc: ",
    issueDatePrefix: "Emissão: ",
    dueDatePrefix: "Venc: ",
    finePrefix: "Multa: ",
    interestPrefix: "Juros: ",
    toSettlePrefix: "A liquidar: ",
    exportReceivablesModalTitle: "Exportar contas a receber",
    exportReceivablesModalSubtitle: "Selecione o formato desejado para exportar a listagem filtrada",
    settleAccountTitle: "Liquidar conta a receber",
    settleAccountSubtitle: "Confirmar recebimento do valor desta conta",
    confirmSettleButton: "Confirmar Liquidação",
    settleSuccessMessage: "Conta liquidada com sucesso!",
  },
  crediario: {
    title: "Crediário e Carnês",
    searchPlaceholder: "Buscar por cliente ou carnê...",
    emptyTitle: "Nenhum crediário ativo",
    emptySubtitle: "Cadastre vendas no crediário para acompanhar as parcelas",
    customerLimitLabel: "Limite de Crédito do Cliente",
    outstandingBalanceLabel: "Saldo Devedor",
    installmentsLabel: "Parcelas",
  },
  returns: {
    title: "Devolução e Trocas",
    filtersPanelTitle: "Filtros",
    searchPlaceholder: "Buscar venda ou comprovante...",
    emptyTitle: "Nenhuma devolução registrada",
    emptySubtitle: "Itens devolvidos e estornos de pagamento serão exibidos aqui",
    returnReasonLabel: "* Motivo da Devolução",
    returnItemsLabel: "Itens a Devolver",
    refundTypeLabel: "Forma de Reembolso",
    addProductTitle: "Deseja adicionar um produto?",
    addProductDesc: "Adiciona o produto na devolução com a quantidade informada",
    productLabel: "Produto",
    productHelp: "Selecione o produto a ser devolvido",
    priceLabel: "Preço Unitário",
    quantityLabel: "Quantidade",
    addProductButton: "Adicionar",
  },
  reports: {
    title: "Relatórios Gerenciais",
    salesReportTitle: "Relatório de Vendas",
    cashReportTitle: "Relatório de Fechamento de Caixa",
    stockReportTitle: "Relatório de Posição de Estoque",
    commissionReportTitle: "Relatório de Comissões",
    startDateLabel: "Data Inicial",
    endDateLabel: "Data Final",
    exportPdfButton: "Exportar PDF",
    exportExcelButton: "Exportar Excel",
    exportCsvButton: "Exportar CSV",
    groupLabel: "Grupo",
    groupPlaceholder: "Todos os grupos",
    subgroupLabel: "Subgrupo",
    subgroupPlaceholder: "Todos os subgrupos",
    clientLabel: "Cliente",
    clientPlaceholder: "Todos os clientes",
    userLabel: "Usuário",
    userPlaceholder: "Todos os usuários",
    deviceLabel: "Dispositivo",
    devicePlaceholder: "Todos os dispositivos",
    costLabel: "Custo",
    orderLabel: "Ordenação",
    azSortButton: "A-Z",
    xmlExportTitle: "Exportação de Arquivos XML",
    xmlExportDesc: "Gere um arquivo ZIP com todos os arquivos XML das notas fiscais emitidas no período.",
    generateZipButton: "Gerar Arquivo ZIP",
  },
  inventory: {
    title: "Estoque",
    newItemTitle: "Novo Item de Estoque",
    editItemTitle: "Editar Item de Estoque",
    searchPlaceholder: "Buscar produto por nome...",
    emptyTitle: "Nenhum produto no estoque",
    emptySubtitle: "Cadastre produtos para gerenciar seu estoque",
    newItemButton: "Novo item",
    nameLabel: "* Nome do Produto",
    namePlaceholder: "Nome do produto",
    quantityLabel: "* Quantidade em Estoque",
    minStockLabel: "Estoque Mínimo",
    deleteItemTitle: "Excluir item de estoque",
    saveItemTitle: "Salvar item",
    stockColumnHeader: "Estoque",
    minStockColumnHeader: "Mínimo",
    unitColumnHeader: "Unidade",
    actionsColumnHeader: "Ações",
    balancoCardTitle: "Balanço de Estoque",
    balancoCardDesc: "Contagem e ajuste de inventário",
    balancoSummaryTitle: "Resumo do Balanço",
    adjustStockButton: "Ajuste de Estoque",
    searchInvoicesPlaceholder: "Buscar notas fiscais...",
    invoicesCardTitle: "Entrada por Nota Fiscal",
    invoicesCardDesc: "Importação de XML e manifesto de notas",
    manualMovementCardTitle: "Entrada / Saída Manual",
    manualMovementCardDesc: "Lançamento avulso de movimentação de estoque",
    invoiceNumberHeader: "Número NF-e",
    supplierIssuerHeader: "Fornecedor / Emitente",
    totalValueHeader: "Valor Total",
    accessKeyHeader: "Chave de Acesso",
    emptyBalancoTitle: "Nenhum balanço encontrado",
    emptyBalancoSubtitle: "Tente ajustar os filtros ao lado ou crie um novo balanço de estoque.",
    differenceHeader: "Diferença",
    selectProductLabel: "Selecionar Produto",
    movementTypeLabel: "Tipo de Movimentação",
    entryPlusOption: "Entrada (+)",
    exitMinusOption: "Saída (-)",
    quantityUnitsLabel: "Quantidade",
    quantityUnitsPlaceholder: "Quantidade em unidades",
    movementReasonLabel: "Motivo / Justificativa",
    movementReasonPlaceholder: "Ex: Ajuste de quebra, consumo da equipe...",
    confirmMovementButton: "Confirmar Movimentação",
    groupsLabel: "Grupos",
    changeGroup: "Alterar",
    allGroupsSelected: "Todos os grupos selecionados",
    productsSectionTitle: "Produtos",
    productFieldLabel: "* Produto",
    searchProductPlaceholder: "Digite o nome ou código de barras...",
    searchProductHelp: "* Busque pela descrição ou código de barras do produto.",
    quantityFieldLabel: "* Quantidade",
    decreaseQuantity: "Diminuir",
    increaseQuantity: "Aumentar",
    noProductsAddedTitle: "Nenhum produto adicionado",
    noProductsAddedSubtitle: "Busque e adicione produtos ao lado para iniciar a contagem.",
    noItemsInAuditTitle: "Nenhum item registrado neste balanço",
    noItemsInAuditSubtitle: "Esta auditoria foi finalizada sem produtos adicionados.",
    removeItemTitle: "Remover produto do balanço",
  },
  negotiations: {
    title: "Negociações",
    searchPlaceholder: "Buscar por código, cliente ou valor...",
    emptyTitle: "Nenhuma negociação encontrada",
    emptySubtitle: "Altere os filtros ou realize novas vendas para visualizá-las aqui",
    saleLabel: "Venda:",
    totalPaidLabel: "Total pago:",
    productsInOrderTitle: "Produtos no pedido",
    noItemsDetailedTitle: "Nenhum item detalhado",
    noItemsDetailedSubtitle: "Esta venda não possui itens registrados.",
    deleteNegotiationTitle: "Excluir negociação",
    confirmDeleteNegotiationSubtitle: "Confirmar exclusão de negociação",
    confirmDeleteButton: "Confirmar Exclusão",
    deleteNegotiationParagraph: "Tem certeza de que deseja excluir esta negociação do sistema? Esta ação não poderá ser desfeita.",
    shareNegotiationTitle: "Compartilhar negociação",
    printReceiptTitle: "Imprimir comprovante",
    periodFilterLabel: "Período",
    clientFilterLabel: "Cliente",
    userFilterLabel: "Usuário",
    deviceFilterLabel: "Dispositivo",
    tableFilterLabel: "Mesa",
    tabFilterLabel: "Comanda",
    tabFilterPlaceholder: "Comanda / Mesa",
    totalFilteredSalesLabel: "Total das negociações filtradas",
    detailSubtitle: "Detalhamento completo dos produtos e pagamentos da negociação",
    registeredCustomerLabel: "Cliente cadastrado",
    salesQuantityLabel: "Qtd. de vendas",
    totalAmountLabel: "Valor total",
    exportSalesModalTitle: "Exportar vendas",
    exportSalesModalSubtitle: "Selecione o formato desejado para exportar a listagem filtrada",
    exportToPdfTitle: "Exportar para PDF",
    exportToPdfSubtitle: "Baixar relatório formatado em documento PDF (A4)",
    exportToCsvTitle: "Exportar para CSV",
    exportToCsvSubtitle: "Baixar planilha de dados brutos (compatível com Excel)",
    generatingExport: "Gerando exportação...",
  },
  productsCatalog: {
    title: "Produtos",
    newProductTitle: "Novo Produto",
    editProductTitle: "Editar Produto",
    searchPlaceholder: "Buscar produto por nome ou categoria...",
    emptyTitle: "Nenhum produto encontrado",
    emptySubtitle: "Tente pesquisar com outro termo ou adicione um novo produto.",
    deleteProductTitle: "Excluir produto",
    saveProductButton: "Salvar Produto",
    searchByNamePlaceholder: "Buscar produto pelo nome...",
    noCategory: "Geral",
    stockDisplay: "{stock} {unit}",
    fiscalConfigTitle: "Configurações Fiscais Padrão",
  },
  cashTotals: {
    title: "Totais em Caixa",
    openingBalanceLabel: "Fundo de Troco (Abertura)",
    cashSalesLabel: "Vendas em Dinheiro",
    cardSalesLabel: "Vendas em Cartão",
    pixSalesLabel: "Vendas via Pix",
    cashWithdrawalsLabel: "Sangrias / Retiradas",
    cashDepositsLabel: "Suprimentos / Entradas",
    currentTotalLabel: "Saldo Atual em Caixa",
    closeRegisterButton: "Fechar Caixa",
    openingTimePrefix: "Abertura: ",
    totalLabel: "Total",
    shareConferenceTitle: "Compartilhar conferência",
    printConferenceTitle: "Imprimir conferência",
    emptyOperationsTitle: "Nenhuma operação registrada",
    emptyOperationsSubtitle: "As movimentações desta forma de pagamento aparecerão listadas aqui.",
    conferenceTitle: "Conferência de Caixa",
    operationsCount: "Qtd. de operações no período: {count}",
  },
  salesHistory: {
    title: "Histórico de Vendas",
    searchPlaceholder: "Buscar vendas por data, valor ou cliente...",
    emptyTitle: "Nenhuma venda registrada",
    emptySubtitle: "As vendas concluídas neste caixa aparecerão listadas aqui",
    viewReceiptButton: "Ver Comprovante",
    cancelSaleButton: "Cancelar Venda",
  },
  auth: {
    title: "Acesso ao Sistema",
    usernameLabel: "* Usuário ou E-mail",
    usernamePlaceholder: "Digite seu usuário",
    passwordLabel: "* Senha",
    passwordPlaceholder: "Digite sua senha",
    loginButton: "Entrar",
    forgotPasswordLink: "Esqueci minha senha",
    operatorRoleLabel: "* Operador do Caixa",
    selectOperatorPlaceholder: "Selecione seu usuário",
    forgotPasswordButton: "Esqueci minha senha",
    switchCnpjButton: "Trocar Empresa (CNPJ)",
  },
  themeCustomizer: {
    title: "Personalização de Tema",
    subtitle: "Ajuste as cores da identidade visual do seu PDV",
    doneButton: "Concluir",
    presetsTitle: "Paletas Prontas (Presets)",
    fineTuningTitle: "Ajuste Fino de Cores",
    restoreButton: "Restaurar Padrão do Sistema",
    primaryColorLabel: "Cor Primária",
    secondaryColorLabel: "Cor Secundária",
    fontLabel: "Tipografia",
    resetButton: "Restaurar Padrões",
    whitelabelTitle: "Identidade Visual (Whitelabel)",
    whitelabelSubtitle: "Personalize as cores da sua marca e logotipo do seu terminal.",
    uploadNewLogoLabel: "Subir Novo Logotipo",
    uploadLogoDragPlaceholder: "Arraste ou clique para enviar imagem",
    previewLogoAlt: "Preview Logo",
    removeLogoButton: "Remover logo",
    systemSettingsTitle: "Configurações do Sistema",
    systemSettingsSubtitle: "Gerencie suas preferências e recursos do terminal.",
    savePreferencesButton: "Salvar preferências",
  },
  companyAccess: {
    title: "Acesso à Empresa",
    systemAccessTitle: "Acesso à Empresa",
    systemAccessDesc: "Informe o CNPJ e a senha de acesso para liberar o PDV",
    companyNameLabel: "* Razão Social / Nome Fantasia",
    companyNamePlaceholder: "Nome da empresa",
    cnpjLabel: "* CNPJ da Empresa",
    cnpjPlaceholder: "00.000.000/0000-00",
    passwordLabel: "* Senha de Acesso",
    passwordPlaceholder: "Digite a senha de acesso",
    accessCodeLabel: "* Código de Acesso",
    accessCodePlaceholder: "Digite o código",
    confirmButton: "Confirmar Acesso",
    authenticatingButton: "Autenticando...",
    unlockButton: "Desbloquear Empresa",
  },
  companyData: {
    logoAlt: "Logo da empresa",
    clickToChangeLogoTitle: "Clique na imagem para alterar o logotipo",
    removeLogoButton: "Remover logo",
    uploadLogoPlaceholder: "Clique ou arraste para enviar o logotipo",
    corporateReasonLabel: "* Razão social",
    tradeNameLabel: "* Nome fantasia",
    cnpjLabel: "CNPJ",
    ieLabel: "IE",
    addressSectionTitle: "Endereço",
    cepLabel: "* CEP",
    streetLabel: "* Logradouro",
    numberLabel: "* Número",
    complementLabel: "Complemento",
    neighborhoodLabel: "* Bairro",
    cityLabel: "* Cidade",
    contactSectionTitle: "Contato",
    contactNameLabel: "Nome",
    contactPhoneLabel: "Telefone",
    saveChangesButton: "Salvar alterações",
  },
  companySync: {
    enableTitle: "Habilitar",
    enableDesc: "Sincronize os dados entre dispositivos.",
    identificationTitle: "Identificação",
    defaultDeviceName: "Dispositivo 16",
    serverEnvironmentTitle: "Ambiente do servidor",
    cloudEnvironment: "Nuvem",
    syncedStatusTitle: "Sincronizado",
    lastCheckText: "Última verificação: 08/07/2026 22:50",
    lastDataUpdateText: "Última atualização de dados: 05/07/2026 07:28",
    syncDisclaimer: "O sistema verifica periodicamente se há novidades. Caso não haja alterações, a data de atualização permanece a mesma.",
  },
  authorizations: {
    title: "Autorizações",
    operatorLabel: "Operador",
    authorizerLabel: "Autorizador",
    deviceLabel: "Dispositivo",
    showDeniedLabel: "Exibir autorizações negadas",
    emptyTitle: "Nenhuma autorização encontrada",
    emptySubtitle: "As solicitações de autorização de supervisor aparecerão listadas aqui",
    supervisorPasswordLabel: "* Senha do Supervisor",
    supervisorPasswordPlaceholder: "Digite a senha",
    confirmButton: "Autorizar",
    cancelButton: "Cancelar",
  },
  backup: {
    title: "Backup e Restauração",
    description: "Exporte uma cópia completa de todos os dados locais (clientes, produtos, vendas, taxas e configurações) em formato JSON para restauração ou contingência.",
    exportButton: "Exportar Backup",
    exportBackupButton: "Exportar Backup Completo",
    inProgressButton: "Exportando...",
    importButton: "Importar Backup",
    lastBackupLabel: "Ultimo backup:",
    backupSuccessTitle: "Backup Concluído",
    backupSuccessSubtitle: "Seus dados foram salvos com sucesso",
    backupSuccessText: "Backup realizado com sucesso!",
  },
  selfService: {
    title: "Autoatendimento",
    enableToggle: "Habilitar Autoatendimento",
    welcomeMessageLabel: "Mensagem de boas-vindas",
    welcomeMessagePlaceholder: "Bem-vindo! Toque para iniciar.",
    inactivityTimeoutLabel: "Tempo de inatividade (segundos)",
    productsSectionTitle: "Produtos",
    productsSelectedDesc: "Selecione quais produtos serão exibidos no totem",
    paymentMethodsTitle: "Formas de Pagamento",
    paymentMethodsDesc: "Formas de pagamento aceitas no terminal",
    cardTitle: "Cartão (Crédito / Débito)",
    cardDesc: "Habilitar pagamento via cartão integrado",
    pixTitle: "Pix",
    pixDesc: "Habilitar pagamento via QR Code Pix no totem",
    optionsSectionTitle: "Opções Gerais",
    customizationPdvTitle: "Personalização do Totem",
    orderNumberTitle: "Número do Pedido",
    nextNumberLabel: "Próximo número a ser gerado",
    nextNumberPlaceholder: "1",
    resetNumberButton: "Reiniciar numeração diária",
    orderNumberScopeNotice: "A numeração de pedidos é controlada individualmente por dispositivo.",
    enableDeliveryOptionsTitle: "Opções de Entrega / Consumo",
    enableDeliveryOptionsDesc: "Permitir que o cliente escolha entre consumir no local ou viagem",
    stockSectionTitle: "Estoque",
    showOnlyInStock: "Exibir apenas produtos com estoque disponível",
    showStockQuantity: "Exibir quantidade em estoque",
    mainPageSectionTitle: "Página Inicial do Totem",
    mainPageSectionDesc: "Escolha qual tela será exibida ao iniciar o autoatendimento",
    productsPageOption: "Catálogo de Produtos",
    summaryPageOption: "Tela de Boas-Vindas / Resumo",
    customizationScopeNotice: "Essas configurações de personalização são aplicadas a todos os totens.",
    enablePixToggle: "Habilitar Pix",
    enableCardToggle: "Habilitar Cartão",
    enableCashToggle: "Habilitar Dinheiro",
    printReceiptToggle: "Imprimir comprovante após pagamento",
    displayModeLabel: "Modo de Exibição",
    landscapeOption: "Horizontal (Paisagem)",
    portraitOption: "Vertical (Retrato)",
    logoLabel: "Logo da Empresa",
    backgroundImageLabel: "Imagem de fundo",
    themeColorLabel: "Cor do tema",
    fontSizeLabel: "Tamanho da fonte",
    showCategoryBarToggle: "Exibir barra de categorias",
    showSearchBarToggle: "Exibir barra de busca",
    showProductImagesToggle: "Exibir imagens dos produtos",
    allowObservationsToggle: "Permitir observações no pedido",
    operatorPasswordLabel: "Senha do operador",
    operatorPasswordPlaceholder: "Senha para acessar o painel",
    linkedDevicesTitle: "Dispositivos Vinculados",
    newDeviceTitle: "Novo Dispositivo",
    editDeviceTitle: "Editar Dispositivo",
    deviceNameLabel: "* Nome do Dispositivo",
    deviceNamePlaceholder: "Ex: Totem 1, Caixa Self-Service",
    emptyDevicesTitle: "Nenhum dispositivo cadastrado",
    emptyDevicesSubtitle: "Adicione dispositivos de autoatendimento para começar.",
    deleteDeviceTitle: "Excluir dispositivo",
    saveDeviceTitle: "Salvar dispositivo",
    newDeviceButton: "Novo dispositivo",
  },
  scales: {
    checkoutScaleTitle: "Balança de checkout",
    enableCheckoutScaleDesc: "Habilite a leitura do peso da balança de checkout conectada ao Caixa. A leitura será feita apenas para unidades com a opção 'Pesado no caixa'.",
    labelScaleTitle: "Balança etiquetadora",
    scaleModelLabel: "Modelo da balança",
    portLabel: "Porta",
    portHelpButton: "Não encontrei a porta de comunicação da minha balança",
    baudRateLabel: "Velocidade de comunicação (baud rates)",
    advancedSettingsTitle: "Configurações avançadas",
    dataBitsLabel: "Data Bits",
    stopBitsLabel: "Stop Bits",
    parityLabel: "Paridade",
    parityNone: "Nenhuma",
    parityOdd: "Ímpar",
    parityEven: "Par",
    testWeightNote: "Para realizar o teste é necessário que algum peso esteja sobre a balança.",
    testConnectionButton: "Testar comunicação",
    barcodeFormatLabel: "Padrão de Código de Barras (Etiqueta)",
    readLabelsTitle: "Leitura de etiquetas de balança",
    barcodeReturnLabel: "Retorno do código de barras",
    weightReturnOption: "Peso do produto (KG)",
    priceReturnOption: "Valor do produto (R$)",
    productsSectionTitle: "Produtos",
    linkedProductsDesc: "0 produtos vinculados.",
    exportProductsTitle: "Exportar produtos",
    exportProductsDesc: "Exporte um arquivo para realizar a carga de produtos no software da balança.",
    infoModalTitle: "Informação",
    infoModalSubtitle: "Status da comunicação",
    exportModalTitle: "Carga de Produtos",
    exportModalSubtitle: "Exportação de carga",
    fizilolaModel: "Filizola",
    toledoModel: "Toledo",
    uranoModel: "Urano",
  },
  onlineCatalog: {
    title: "Catálogo Online",
    enableDesc: "Você terá uma página na internet com os seus produtos e com a cara da sua loja.",
    openInBrowserTooltip: "Abrir no navegador",
    copyUrlTooltip: "Copiar URL",
    copiedTooltip: "Copiado!",
    identificationTitle: "Identificação",
    identificationSlug: "basenavelo",
    productsTitle: "Produtos",
    productsSelectedCount: "52 produtos selecionados",
    searchProductOrCategoryPlaceholder: "Buscar produto por nome ou categoria...",
    productsSelectDesc: "Selecione os produtos que ficarão visíveis no Catálogo Online",
    selectAllLabel: "Selecionar todos os produtos",
    noProductsFoundTitle: "Nenhum produto encontrado",
    noProductsFoundSubtitle: "Tente buscar com outro termo",
    selectedProductsCountTemplate: "{count} produtos selecionados",
    businessHoursTitle: "Horário de atendimento",
    everydayText: "Todos os dias",
    paymentMethodsTitle: "Formas de pagamento",
    whatsappTitle: "WhatsApp",
    whatsappDesc: "Ative esta opção para enviar notificações automáticas para os clientes.",
    enabledBadge: "habilitado",
    deliveryOptionsTitle: "Opções de entrega",
    orderOptionsTitle: "Opções de pedido",
    loginTitle: "Login",
    loginDesc: "Será obrigatório o login para realizar pedidos e acessar histórico, cartões e endereços.",
  },
  cities: {
    title: "Cidades Atendidas",
    newCityTitle: "Nova Cidade",
    editCityTitle: "Editar Cidade",
    searchPlaceholder: "Buscar cidade...",
    emptyTitle: "Nenhuma cidade cadastrada",
    emptySubtitle: "Cadastre as cidades que sua empresa atende para habilitar a entrega.",
    newCityButton: "Nova cidade",
    stateLabel: "* Estado",
    cityLabel: "* Cidade",
    deliveryFeeLabel: "Taxa de Entrega (R$)",
    deliveryFeePlaceholder: "0,00",
    estimatedTimeLabel: "Tempo Estimado (min)",
    estimatedTimePlaceholder: "45",
    deleteCityTitle: "Excluir cidade",
    saveCityTitle: "Salvar cidade",
    stateColumnHeader: "Estado",
    cityColumnHeader: "Cidade",
    feeColumnHeader: "Taxa",
    timeColumnHeader: "Tempo",
    actionsColumnHeader: "Ações",
    addCityButton: "Adicionar cidade",
    deleteCityConfirmTitle: "Excluir Cidade",
    deleteCityConfirmSubtitle: "Confirmar exclusão de cidade",
    deleteCityConfirmParagraph: "Tem certeza que deseja excluir esta cidade?",
    cityNameLabel: "* Nome da Cidade",
    cityNamePlaceholder: "Ex: São Paulo, Rio de Janeiro",
    stateUfLabel: "* Estado (UF)",
    saveCityButton: "Salvar Cidade",
  },
  receipts: {
    title: "Comprovantes",
    headerDesc: "Defina quais comprovantes serão impressos automaticamente pelo sistema",
    cancellationTitle: "Cancelamento",
    cancellationDesc: "Imprimir comprovante ao cancelar uma venda",
    carneTitle: "Carnê de pagamento",
    cashClosingTitle: "Fechamento de caixa",
    danfeSimplifiedTitle: "DANFE Simplificado NF-e",
    danfeSimplifiedDesc: "Imprimir DANFE simplificado em impressora térmica",
    nfceTitle: "NFC-e",
    newReceiptTitle: "Novo Modelo de Comprovante",
    editReceiptTitle: "Editar Modelo de Comprovante",
    searchPlaceholder: "Buscar modelos...",
    emptyTitle: "Nenhum modelo de comprovante cadastrado",
    emptySubtitle: "Crie modelos personalizados para os comprovantes de venda",
    newReceiptButton: "Novo modelo",
    nameLabel: "* Nome do Modelo",
    namePlaceholder: "Ex: Comprovante Padrão, Cupom Simplificado",
    showLogoToggle: "Exibir logo da empresa",
    showAddressToggle: "Exibir endereço",
    showCNPJToggle: "Exibir CNPJ",
    showDateTimeToggle: "Exibir data e hora",
    showOperatorToggle: "Exibir operador",
    showTableToggle: "Exibir mesa/comanda",
    showItemDetailsToggle: "Exibir detalhes dos itens",
    showDiscountToggle: "Exibir descontos",
    showTaxesToggle: "Exibir taxas",
    showPaymentMethodToggle: "Exibir forma de pagamento",
    showChangeToggle: "Exibir troco",
    footerMessageLabel: "Mensagem de rodapé",
    footerMessagePlaceholder: "Ex: Obrigado pela preferência!",
    deleteReceiptTitle: "Excluir modelo",
    saveReceiptTitle: "Salvar modelo",
    orderNumberTitle: "Número de atendimento",
    orderNumberDesc: "Imprimir comprovante com número de atendimento",
    orderServiceTitle: "Pedido de atendimento",
    orderServiceDesc: "Imprimir pedido detalhado para produção/cozinha",
    pixTitle: "Pix",
    crediarioTitle: "Recebimento de crediário",
    sangriaTitle: "Sangria",
    suprimentoTitle: "Suprimento",
    ticketTitle: "Ticket",
    ticketDesc: "Imprimir ticket numerado para retirada",
    posTransactionTitle: "Transação POS",
    posTransactionDesc: "Imprimir comprovante da maquininha integrada",
    saleTitle: "Venda",
    settingsCardTitle: "Configurações Gerais",
    logoTitle: "Logomarca",
    logoDesc: "Imprimir logotipo no topo dos comprovantes",
  },
  driverConnect: {
    title: "Conecta Entregador",
    enableToggle: "Habilitar Conecta Entregador",
    enableDesc: "Permite que entregadores recebam e gerenciem pedidos pelo aplicativo.",
    driversShortcutTitle: "Entregadores",
    driversLinkedCount: "Nenhum entregador vinculado",
    realtimeLocationTitle: "Localização em Tempo Real",
    googleMapsKeyLabel: "Chave da API do Google Maps",
    googleMapsKeyPlaceholder: "Chave da API do Google Maps",
    howToGetKeyText: "Não sabe como obter uma chave da API do Google Maps? ",
    clickHereText: "Clique aqui",
    allowTrackingLabel: "Permitir que o cliente acompanhe a rota do entregador em tempo real",
    syncTitle: "Sincronização",
    syncDesc: "Selecione o dispositivo que enviará os dados aos entregadores",
    syncDeviceTitle: "Dispositivo de sincronização",
    paymentMethodsTitle: "Formas de Pagamento Aceitas",
    moneyToggle: "Dinheiro",
    cardToggle: "Cartão",
    pixToggle: "Pix",
    maxDeliveriesLabel: "Máximo de entregas simultâneas por entregador",
    trackingToggle: "Habilitar rastreamento de entregadores",
    signatureToggle: "Exigir assinatura do cliente na entrega",
    photoToggle: "Exigir foto da entrega",
    driverRatingToggle: "Habilitar avaliação do entregador",
    notificationToggle: "Enviar notificação ao cliente sobre status da entrega",
  },
  tabsConfig: {
    title: "Comandas",
    newTabTitle: "Nova Comanda",
    editTabTitle: "Editar Comanda",
    searchPlaceholder: "Buscar comanda...",
    emptyTitle: "Nenhuma comanda cadastrada",
    emptySubtitle: "Cadastre comandas para gerenciar o lançamento de pedidos.",
    tabsTableTitle: "Comandas",
    tabNumberLabel: "* Número da Comanda",
    tabNumberPlaceholder: "Ex: 1, 2, 3...",
    addTabButton: "Adicionar comanda",
    identificationCol: "Identificação",
    statusCol: "Status",
    actionsCol: "Ações",
    tabItemNameTemplate: "Comanda {number}",
    statusAvailable: "Disponível",
    statusInUse: "Em uso",
    deleteConfirmTitle: "Excluir Comanda",
    deleteConfirmSubtitle: "Confirmar exclusão de comanda",
    deleteConfirmParagraph: "Tem certeza que deseja excluir esta comanda?",
    maxTabsLabel: "Quantidade Máxima de Comandas",
    requireCustomerLabel: "Exigir identificação de cliente ao abrir comanda",
    prefixLabel: "Prefixo da Comanda",
  },
  priceCheck: {
    title: "Consulta Preço",
    authTitle: "Autenticação",
    passwordLabel: "* Senha",
    passwordPlaceholder: "Senha",
    authDesc: "Cadastre a senha que será utilizada para acessar as configurações do aplicativo Consulta Preço.",
    linkedDevicesTitle: "Dispositivos vinculados",
    linkDeviceButton: "Vincular dispositivo",
    emptyTitle: "Nenhum dispositivo vinculado",
    emptySubtitle: "Vincule um dispositivo para disponibilizar o Consulta Preço.",
    deviceCodeTemplate: "Código: {code}",
    barcodeInputLabel: "Código de Barras ou Nome do Produto",
    barcodePlaceholder: "Bipe o código de barras ou digite...",
    checkPriceButton: "Consultar Preço",
    productFoundTitle: "Produto Localizado",
    priceLabel: "Preço de Venda",
  },
  digitalAccount: {
    title: "Conta Digital",
    enableToggle: "Habilitar",
    enableDesc: "Use a Conta Digital para receber pagamentos",
    accessPlatformButton: "Acessar a plataforma Conta Digital",
    cashierCardTitle: "Caixa",
    cashierCardDesc: "Defina as formas de pagamento que serão aplicadas no Caixa",
    catalogCardTitle: "Catálogo Online",
    catalogCardDesc: "Defina as formas de pagamento que serão aplicadas na página do seu Catálogo Online",
    driverCardTitle: "Conecta Entregador",
    driverCardDesc: "Defina as formas de pagamento que serão aplicadas no aplicativo Conecta Entregador",
    selfServiceCardTitle: "Autoatendimento",
    selfServiceCardDesc: "Defina as formas de pagamento que serão aplicadas no Autoatendimento",
    pixLabel: "Pix",
    cardLabel: "Cartão",
    balanceLabel: "Saldo Disponível",
    extractTitle: "Extrato de Movimentações",
    transferButton: "Fazer Transferência",
    pixKeyLabel: "Chave Pix da Conta",
  },
  deliveryFees: {
    emptyTitle: "Nenhuma taxa de entrega cadastrada",
    emptySubtitle: "Cadastre taxas de entrega para gerenciar os custos de envio dos seus pedidos.",
    addFeeButton: "Adicionar taxa de entrega",
    addFeeFormButton: "Adicionar taxa",
    nameLabel: "* Nome",
    namePlaceholder: "Ex: Taxa Centro, Bairro Norte",
    valueLabel: "* Valor (R$)",
    valuePlaceholder: "0,00",
    nameColumnHeader: "Nome",
    valueColumnHeader: "Valor",
    actionsColumnHeader: "Ações",
    searchPlaceholder: "Buscar por região ou bairro...",
    rateDataTitle: "Dados da taxa de entrega",
    regionNameLabel: "* Nome da Região / Bairro",
    regionNamePlaceholder: "Ex: Região Metropolitana, Centro, Bairro Alto",
    rateValueLabel: "* Valor da Taxa (R$)",
    rateValuePlaceholder: "0,00",
    deleteRateTitle: "Excluir taxa",
    saveRateButton: "Salvar taxa de entrega",
    emptySubtitleFab: "Clique no botão + abaixo para cadastrar uma nova taxa de entrega.",
    newRateFabTitle: "Nova Taxa",
  },
  serviceCharges: {
    emptyTitle: "Nenhuma taxa de serviço cadastrada",
    emptySubtitle: "Cadastre taxas de serviço (fixas ou percentuais) para aplicar aos atendimentos.",
    addFeeButton: "Adicionar taxa de serviço",
    addFeeFormButton: "Adicionar taxa",
    nameLabel: "* Nome",
    namePlaceholder: "Ex: Taxa de Serviço 10%",
    chargeTypeLabel: "Tipo de taxa",
    percentualOption: "Percentual (%)",
    fixedOption: "Valor Fixo (R$)",
    percentualLabel: "* Percentual (%)",
    fixedLabel: "* Valor Fixo (R$)",
    percentualPlaceholder: "10,00",
    fixedPlaceholder: "R$ 0,00",
    nameColumnHeader: "Nome",
    typeColumnHeader: "Tipo",
    valueColumnHeader: "Valor",
    actionsColumnHeader: "Ações",
  },
  credit: {
    interestTypeTitle: "Tipo de juros",
    simpleOption: "Simples",
    compoundOption: "Compostos",
    interestRateLabel: "Juros",
    interestRatePlaceholder: "% 0,00",
    fineRateLabel: "Multa",
    fineRatePlaceholder: "% 0,00",
    graceDaysTitle: "* Dias de carência",
  },
  vendas: {
    clientLabel: "Cliente",
    clientPlaceholder: "Cliente",
    userLabel: "Usuário",
    userPlaceholder: "Usuário",
    deviceLabel: "Dispositivo",
    devicePlaceholder: "Dispositivo",
    filtersPanelTitle: "Filtros",
  },
  pagamentoIntegrado: {
    posLinkedTitle: "POS's vinculados",
    posLinkedWithColonTitle: "POS's vinculados:",
    emptyPosTitle: "Nenhum POS vinculado.",
    emptyPosSubtitle: "Vincule um dispositivo POS para realizar pagamentos.",
    deviceNameNote: "Nome que será exibido no aplicativo \"Pagamento Integrado\".",
  },
  sangrias: {
    sectionTitle: "Sangrias e suprimentos",
  },
  products: {
    title: "Produtos",
    noPhoto: "Sem Foto",
    fiscalConfigTitle: "Configuração Fiscal Padrão",
    form: {
      basicDataTab: "Dados Básicos",
      advancedResourcesTab: "Recursos Avançados",
      imageUploadTitle: "Clique para enviar ou alterar a imagem",
      photoAlt: "Foto do produto",
      changeImage: "Alterar Imagem",
      addImage: "Adicionar Imagem",
      nameLabel: "Descrição (Nome do Produto) *",
      namePlaceholder: "Ex: COCA-COLA LATA 350ML",
      unitLabel: "Unidade *",
      noUnitsRegistered: "Nenhuma unidade cadastrada",
      groupLabel: "Grupo *",
      noGroupsRegistered: "Nenhum grupo cadastrado",
      subgroupLabel: "Subgrupo *",
      noSubgroupsRegistered: "Nenhum subgrupo cadastrado",
      detailedDescriptionLabel: "Descrição Detalhada para Catálogo",
      detailedDescriptionPlaceholder: "Ex: Bebida refrescante gaseificada, lata 350ml...",
      valuesAndStockTitle: "Valores e Estoque",
      stockLabel: "Estoque *",
      minStockLabel: "Estoque Mínimo",
      costPriceLabel: "Preço de Custo (R$)",
      otherCostsLabel: "Outros Custos (%)",
      marginLabel: "Margem (%)",
      salePriceLabel: "Preço de Venda (R$) *",
      zeroPlaceholder: "0",
      zeroDecimalPlaceholder: "0,00",
      multissaborTitle: "Multissabor",
      enableMultissaborTitle: "Habilitar Multissabor",
      enableMultissaborDesc: "Permite que o produto seja fracionado em diferentes sabores",
      multissaborLimitLabel: "Limite Máximo de Sabores",
      pricingModeLabel: "Cobrança da Precificação",
      proportionalAverageOption: "Proporcional (Média)",
      highestPriceOption: "Pelo Maior Preço",
      subgroupComplementsTitle: "Complementos do subgrupo",
      linkComplementsTitle: "Vincular Complementos",
      linkComplementsDesc: "Vincular opcionais e acompanhamentos cadastrados no subgrupo",
      salesPlatformsTitle: "Plataformas de venda",
      showInOnlineCatalogTitle: "Exibir no Catálogo Online",
      showInOnlineCatalogDesc: "Habilita a exibição do produto em vendas digitais",
      catalogPriceLabel: "Preço Diferente para Catálogo (R$)",
      barcodesTitle: "Códigos de barras",
      addBarcodeLabel: "Adicionar Novo EAN / GTIN",
      barcodePlaceholder: "Ex: 7891234567890",
      registeredBarcodesTitle: "Códigos Cadastrados",
      printPointTitle: "Ponto de impressão",
      printDestinationLabel: "Destino de Impressão",
      noPrintOption: "Sem Impressão",
      productionTitle: "Produção",
      inHouseProductionTitle: "Produção Própria",
      inHouseProductionDesc: "Habilite se o item for de fabricação interna (KDS)",
      ingredientsLabel: "Ingredientes (Ficha Técnica)",
      ingredientsPlaceholder: "Ex: Pão brioche, blend de carne 150g, queijo cheddar...",
      preparationModeLabel: "Modo de Preparo (KDS)",
      preparationModePlaceholder: "Ex: Selar o pão na manteiga, fritar o blend por 3 min de cada lado...",
      fiscalTitle: "Fiscal",
      ncmLabel: "NCM (Nomenclatura Comum do Mercosul)",
      ncmPlaceholder: "Ex: 2202.10.00",
      exTipiLabel: "EX TIPI",
      exTipiPlaceholder: "Exceção do IPI",
      cestLabel: "CEST (Substituição Tributária)",
      cestPlaceholder: "Ex: 17.111.00",
      originLabel: "Origem da Mercadoria *",
      originNational: "0 - Nacional",
      originImported: "1 - Importada Direta",
      originImportedFull: "1 - Estrangeira Importada",
      useDefaultIcmsTitle: "Utilizar ICMS Padrão",
      useDefaultIcmsDesc: "Herda as definições fiscais padrão da filial",
      csosnIcmsLabel: "CSOSN ICMS",
      csosn101Short: "101 - Simples Nacional sem crédito",
      csosn500Short: "500 - Substituição Tributária",
      reductionBaseShortLabel: "Redução Base Cálculo (%)",
      aliquotEffectiveLabel: "Alíquota Efetiva (%)",
      useDefaultPisCofinsTitle: "Utilizar PIS/COFINS Padrão",
      useDefaultPisCofinsDesc: "Herda as definições de PIS/COFINS padrão da filial",
      cstPisCofinsLabel: "CST PIS/COFINS",
      pis49Short: "49 - Outras Op. de Saída",
      pis99Short: "99 - Outras Operações",
      accessFiscalConfigButton: "Acessar configuração fiscal padrão",
    },
  },
  posLink: {
    defaultModalTitle: "Vincular Dispositivo",
    modalSubtitle: "Vincule um dispositivo ao aplicativo",
    linkingCodeLabel: "Código de vinculação",
    linkingCodeRequiredLabel: "* Código de vinculação",
    linkingCodePlaceholder: "Digite o código de vinculação",
    linkingCodeHelpText: "Informe o código apresentado no aplicativo",
    deviceNameRequiredLabel: "* Nome do dispositivo",
    deviceNamePlaceholder: "Nome do dispositivo",
    linkButton: "VINCULAR",
  },
  cashManagement: {
    availableInCash: "Disponível em caixa",
  },
  scanner: {
    scanProductTitle: "Escanear produto",
    scannerUnavailableTitle: "Leitor indisponível",
    scannerUnavailableSubtitle: "Seu navegador não suporta leitura de código de barras pela câmera.",
    cameraUnavailableTitle: "Câmera indisponível",
    pointCameraInstruction: "Aponte a câmera para o código de barras do produto.",
  },
  saleShare: {
    sendLinkModalTitle: "Enviar Link de Download",
    scanQrInstruction: "Escaneie para baixar o comprovante",
    receiptLinkLabel: "Link do comprovante",
    copiedTooltip: "Copiado!",
    copyLinkTooltip: "Copiar link",
    sendViaWhatsApp: "Enviar via WhatsApp",
    recipientNumberLabel: "Número do destinatário",
    phonePlaceholder: "(11) 99999-9999",
    phoneHelpText: "Informe o DDD e o número do celular",
    shareReceiptModalTitle: "Compartilhar Comprovante",
    generatingPdf: "Gerando PDF...",
    saveFile: "Salvar arquivo",
    downloadPdfDevice: "Download do PDF no dispositivo",
    sendDownloadLink: "Enviar link de download",
    shareQrOrWhatsApp: "Compartilhe via QR Code ou WhatsApp",
  },
  admin: {
    header: {
      title: "Navelo Admin",
      subtitle: "Painel de Controle do SaaS",
      toggleValuesTitle: "Ocultar/Mostrar Valores",
      logoutTitle: "Sair",
      syncedTitle: "Sincronizado",
      outOfSyncTitle: "Fora de sincronização",
    },
    dashboard: {
      title: "Olá, Administrador 👋",
      description: "Selecione o módulo que deseja acessar para gerenciar a plataforma.",
      activitiesTitle: "Atividades Recentes",
      activitiesDescription: "Últimos 5 logs registrados na plataforma.",
    },
    auth: {
      title: "Autenticação Administrativa",
      description: "Insira suas credenciais de super-admin",
      emailLabel: "E-mail",
      emailPlaceholder: "admin@navelo.com",
      passwordLabel: "Senha",
      passwordPlaceholder: "••••••••",
      submitButton: "Acessar plataforma",
    },
    plans: {
      backButton: "Voltar ao Painel",
      title: "CRUD de Planos e Features",
      description: "Gerencie os níveis de assinatura e quais módulos cada plano pode acessar.",
      newPlanButton: "Novo Plano",
      searchPlaceholder: "Buscar plano por nome...",
      emptyTitle: "Nenhum plano encontrado",
      emptySubtitle: "Nenhum plano corresponde ao termo pesquisado.",
      planNameColumn: "Nome do Plano",
      monthlyPriceColumn: "Preço Mensal",
      activeModulesColumn: "Módulos Ativos",
      statusColumn: "Status",
      actionsColumn: "Ações",
      deleteConfirmTitle: "Excluir Plano",
      deleteConfirmSubtitle: "Confirmar exclusão de plano",
      deleteConfirmParagraph: "Tem certeza que deseja excluir este plano de assinatura?",
      editPlanTitle: "Editar Plano",
      createPlanTitle: "Criar Novo Plano",
      planModalSubtitle: "Preencha os dados e escolha os recursos liberados para esta assinatura.",
      saveChangesButton: "Salvar Alterações",
      savePlanButton: "Salvar Plano",
      planNameLabel: "Nome do Plano",
      planNamePlaceholder: "Ex: Plano Intermediário",
      monthlyPriceLabel: "Preço Mensal (R$)",
      monthlyPricePlaceholder: "Ex: 99.90",
      includedModulesLabel: "Módulos Inclusos",
    },
    audit: {
      backButton: "Voltar ao Painel",
      title: "Logs de Auditoria",
      description: "Histórico completo e imutável de eventos disparados no sistema.",
      historyTitle: "Histórico de Atividades",
      historyDescription: "Histórico de eventos e auditoria de ações na plataforma.",
      refreshButton: "Atualizar",
      searchPlaceholder: "Buscar por usuário, tenant ou ação...",
      searchLogsPlaceholder: "Buscar por ação, tipo de entidade ou IP...",
      emptyTitle: "Nenhum log de auditoria encontrado",
      emptySubtitle: "Nenhuma atividade corresponde aos filtros aplicados.",
      emptyLogsTitle: "Nenhum log encontrado",
      emptyLogsSubtitle: "Nenhum evento corresponde ao termo pesquisado.",
      timestampColumn: "Data/Hora",
      tenantColumn: "Tenant (Empresa)",
      userColumn: "Usuário",
      actionColumn: "Ação Realizada",
      actionTextColumn: "Ação",
      entityColumn: "Entidade",
      ipColumn: "IP",
      severityColumn: "Severidade",
      detailsColumn: "Detalhes do Evento",
      errorSeverity: "ERRO",
      warningSeverity: "ALERTA",
      infoSeverity: "INFO",
    },
    reports: {
      backButton: "Voltar ao Painel",
      title: "Relatórios e Métricas Globais",
      description: "Métricas agregadas do ecossistema SaaS.",
      metricsTitle: "Métricas Financeiras Globais",
      metricsDescription: "Consolidação de receitas, MRR, churn e crescimento.",
      exportPdfButton: "Exportar PDF",
      mrrCardTitle: "MRR (Receita Mensal)",
      mrrCardSubtitle: "Crescimento de +12.4% este mês",
      arrCardTitle: "ARR (Receita Anualizada)",
      arrCardSubtitle: "Previsão baseada no MRR atual",
      ltvCardTitle: "LTV Médio (Tempo de Vida)",
      ltvCardSubtitle: "Ticket médio acumulado por tenant",
      revenueTitle: "Receita por Locatário",
      revenueDescription: "Faturamento detalhado por cada empresa cadastrada.",
      companyColumn: "Empresa",
      planColumn: "Plano Contratado",
      annualRevenueColumn: "Faturamento Anual Previsto",
      monthlyRevenueColumn: "Faturamento Mensal",
      mrrTitle: "Receita Mensal Recorrente (MRR)",
      activeTenantsTitle: "Empresas Ativas",
      subscriptionsTitle: "Assinaturas no Período",
      distributionTitle: "Distribuição de Assinantes por Plano",
      mrrLabel: "MRR",
      tenantsLabel: "Empresas",
      churnLabel: "Cancelamentos",
      conversionLabel: "Taxa de Conversão",
      periodLabel: "Período",
      periodPlaceholder: "Selecione o período",
    },
    tenants: {
      backButton: "Voltar ao Painel",
      title: "Gerenciamento de Tenants (Empresas)",
      description: "Crie, edite e alterne entre as empresas cadastradas no sistema.",
      tenantsListTitle: "Lista de Empresas (Tenants)",
      tenantsListDescription: "Gerencie as contas de inquilinos, dados fiscais e status das licenças.",
      newTenantButton: "Novo Tenant",
      newCompanyButton: "Nova Empresa",
      searchPlaceholder: "Buscar tenant por nome, domínio ou CNPJ...",
      searchTenantsPlaceholder: "Buscar por nome da empresa, CNPJ ou cidade...",
      emptyTitle: "Nenhum tenant cadastrado",
      emptySubtitle: "Clique no botão acima para cadastrar a primeira empresa.",
      emptyCompaniesTitle: "Nenhuma empresa encontrada",
      emptyCompaniesSubtitle: "Nenhuma empresa corresponde ao termo pesquisado.",
      nameColumn: "Empresa",
      subdomainColumn: "Subdomínio",
      cnpjColumn: "CNPJ",
      cnpjCpfColumn: "CNPJ / CPF",
      cityStateColumn: "Cidade/UF",
      planColumn: "Plano",
      statusColumn: "Status",
      monthlyFeeColumn: "Mensalidade",
      unnamedCompany: "Empresa sem nome",
      createdAtColumn: "Criado em",
      actionsColumn: "Ações",
      deleteConfirmTitle: "Excluir Tenant",
      deleteConfirmSubtitle: "Confirmar exclusão de tenant",
      deleteConfirmParagraph: "Tem certeza que deseja excluir esta empresa?",
      newTenantModalTitle: "Cadastrar Nova Empresa (Tenant)",
      editTenantModalTitle: "Editar Empresa (Tenant)",
      newCompanyModalTitle: "Nova Empresa (Conta)",
      newCompanyModalSubtitle: "Cadastre todos os dados da empresa cliente para emissão de comprovantes e controle de licença.",
      saveCompanyButton: "Salvar Empresa",
      companyIdentification: "Identificação da Empresa",
      companyNameRequired: "Razão Social *",
      companyNamePlaceholder: "Ex: NAVELO SISTEMAS LTDA",
      companyTradeName: "Nome Fantasia",
      companyTradeNamePlaceholder: "Ex: Navelo PDV",
      cnpjCpfRequired: "CNPJ / CPF *",
      stateRegistration: "Inscrição Estadual (IE)",
      stateRegistrationPlaceholder: "Ex: 001234567.00-88",
      commercialContact: "Contato Comercial",
      phoneWhatsapp: "Telefone / WhatsApp",
      contactEmail: "E-mail de Contato",
      contactEmailPlaceholder: "contato@empresa.com.br",
      commercialAddress: "Endereço Comercial",
      cepLabel: "CEP",
      cepPlaceholder: "00000-000",
      streetLabel: "Logradouro / Rua",
      streetPlaceholder: "Ex: Rua Sagrada Família",
      numberLabel: "Número",
      numberPlaceholder: "Ex: 94 ou S/N",
      complementLabel: "Complemento",
      complementPlaceholder: "Ex: Sala 102, Bloco B",
      neighborhoodLabel: "Bairro",
      neighborhoodPlaceholder: "Ex: Ipiranga",
      cityLabel: "Cidade",
      cityPlaceholder: "Ex: Teófilo Otoni",
      ufLabel: "UF",
      ufPlaceholder: "MG",
      licenseAndStatus: "Licença e Status",
      billingPlanBadge: "Plano de Cobrança",
      initialStatusBadge: "Status Inicial da Conta",
      tenantModalSubtitle: "Preencha as informações cadastrais e selecione o plano de assinatura.",
      nameLabel: "* Razão Social / Nome Fantasia",
      namePlaceholder: "Ex: Restaurante Bella Vista Ltda",
      subdomainLabel: "* Subdomínio",
      subdomainPlaceholder: "Ex: bellavista",
      cnpjCpfLabel: "* CNPJ ou CPF",
      cnpjCpfPlaceholder: "00.000.000/0000-00",
      planLabel: "* Plano de Assinatura",
      statusLabel: "* Status da Conta",
      adminEmailLabel: "* E-mail do Administrador da Empresa",
      adminEmailPlaceholder: "admin@empresa.com",
      createTenantButton: "Criar Empresa",
      saveChangesButton: "Salvar Alterações",
      activeOption: "Ativo",
      suspendedOption: "Suspenso",
      trialOption: "Trial",
      canceledOption: "Cancelado",
      switchTenantButton: "Acessar Loja",
    },
    users: {
      backButton: "Voltar ao Painel",
      title: "Usuários e Acessos",
      description: "Gerencie os operadores e administradores cadastrados na plataforma.",
      userManagementTitle: "Gestão de Usuários",
      userManagementDesc: "Lista de logins, convite de novos membros e concessão de cargos.",
      newUserButton: "Novo Usuário",
      searchPlaceholder: "Buscar usuário por nome ou e-mail...",
      searchUsersPlaceholder: "Buscar por nome, email ou empresa...",
      emptyTitle: "Nenhum usuário encontrado",
      emptySubtitle: "Nenhum operador corresponde aos critérios pesquisados.",
      emptyUsersTitle: "Nenhum usuário encontrado",
      emptyUsersSubtitle: "Nenhum usuário corresponde ao termo pesquisado.",
      nameColumn: "Nome",
      emailColumn: "E-mail",
      companyColumn: "Empresa",
      roleColumn: "Perfil de Acesso",
      roleHeader: "Cargo",
      statusColumn: "Status",
      actionsColumn: "Ações",
      deleteConfirmTitle: "Excluir Usuário",
      deleteConfirmSubtitle: "Confirmar exclusão de usuário",
      deleteConfirmParagraph: "Tem certeza que deseja excluir este usuário?",
      newUserModalTitle: "Novo Usuário",
      editUserModalTitle: "Editar Usuário",
      newUserModalSubtitle: "Cadastre uma credencial e associe a uma empresa.",
      userModalSubtitle: "Preencha os dados do operador ou administrador.",
      saveUserButton: "Salvar Usuário",
      fullNameLabel: "Nome Completo",
      fullNamePlaceholder: "Nome do colaborador",
      emailAddressLabel: "Endereço de E-mail",
      emailAddressPlaceholder: "exemplo@empresa.com",
      tenantBadgeLabel: "Empresa Inquilina",
      roleBadgeLabel: "Cargo / Nível de Acesso",
      adminRole: "Administrador",
      managerRole: "Gerente",
      cashierRole: "Caixa",
      attendantRole: "Atendente",
      nameLabel: "* Nome Completo",
      namePlaceholder: "Ex: João Silva",
      emailLabel: "* E-mail",
      emailPlaceholder: "joao@empresa.com",
      roleLabel: "* Perfil",
      passwordLabel: "* Senha de Acesso",
      passwordPlaceholder: "Digite a senha do usuário",
    },
    clients: {
      backButton: "Voltar ao Painel",
      title: "Lista de Locatários",
      description: "Gerencie as contas de inquilinos e status das licenças.",
      newTenantButton: "Novo Inquilino",
      searchPlaceholder: "Buscar por nome da empresa ou documento...",
      emptyTitle: "Nenhum inquilino encontrado",
      emptySubtitle: "Nenhuma empresa corresponde ao termo pesquisado.",
      companyColumn: "Empresa",
      documentColumn: "Documento",
      planColumn: "Plano",
      statusColumn: "Status",
      monthlyFeeColumn: "Mensalidade",
      newClientModalTitle: "Novo Cliente Locatário",
      newClientModalSubtitle: "Cadastre manualmente uma empresa cliente do SaaS.",
      saveTenantButton: "Salvar Inquilino",
      companyNameLabel: "Nome da Empresa",
      companyNamePlaceholder: "Nome fantasia ou Razão Social",
      cnpjDocumentLabel: "CNPJ / Documento",
      cnpjDocumentPlaceholder: "Ex: 00.000.000/0000-00",
      billingPlanBadge: "Plano de Cobrança",
      initialActiveStatusBadge: "Status Inicial Ativo",
      activeStatus: "Ativo",
      inactiveStatus: "Inativo",
      freeFee: "Grátis",
    },
    settings: {
      backButton: "Voltar ao Painel",
      title: "Configurações da Plataforma",
      description: "Configurações globais do sistema SaaS.",
      systemParamsTitle: "Parâmetros do Sistema",
      systemParamsDesc: "Defina os parâmetros operacionais da plataforma SaaS.",
      platformNameLabel: "Nome da Plataforma",
      platformNamePlaceholder: "Digite o nome da plataforma",
      adminEmailSupportLabel: "E-mail de Suporte Administrativo",
      adminEmailSupportPlaceholder: "Ex: suporte@empresa.com",
      allowRegistrationLabel: "Permitir novos cadastros",
      allowRegistrationDesc: "Novos locatários podem se registrar de forma autônoma.",
      maintenanceModeLabel: "Modo de manutenção",
      maintenanceModeDesc: "Bloqueia temporariamente o acesso de todos os inquilinos.",
      visualIdentityTitle: "Identidade Visual & Cores (Whitelabel)",
      visualIdentityDesc: "Personalize as cores e o logotipo de sua plataforma.",
      primaryColorLabel: "Cor Primária (Tema)",
      secondaryColorLabel: "Cor Secundária (Destaques)",
      platformLogoLabel: "Logotipo da Plataforma",
      platformLogoPlaceholder: "Clique ou arraste para enviar logotipo customizado",
      removeLogoButton: "Remover Logotipo",
      saveChangesButton: "Salvar Alterações",
      generalTab: "Geral",
      integrationsTab: "Integrações",
      securityTab: "Segurança",
      saveButton: "Salvar Configurações",
    },
  },
  misc: {
  },
} as const

export type UIStrings = typeof UI_STRINGS

/**
 * Utilitário para interpolação de strings dinâmicas com tags nomeadas {key}.
 * Exemplo: formatString(UI_STRINGS.dashboard.stockLowTitle, { product: "Coca Cola" })
 */
export function formatString(template: string, values: Record<string, string | number>): string {
  let result = template
  for (const [key, value] of Object.entries(values)) {
    result = result.replace(new RegExp(`\\{${key}\\}`, "g"), String(value))
  }
  return result
}

